/* File: "ext_ident_double_506_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: sq",color=plum, style=filled]
0 -> 1
2 [label="op2: *",color=green4, style=filled]
1 -> 2
3 [label="ext_ident_double_497",color=cyan4, style=filled]
2 -> 3
293 [label="ext_ident_double_505",color=cyan4, style=filled]
2 -> 293


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((ext_ident_double_497) * (ext_ident_double_505))));
*/
SDouble ext_ident_double_506_arg0(const SDouble ext_ident_double_497,
                                  const SWord64 ext_ident_word64_490,
                                  const SDouble ext_ownship_position_z,
                                  const SWord64 ext_ident_word64_491,
                                  const SWord64 ext_ident_word64_492,
                                  const SWord64 ext_ident_word64_493,
                                  const SWord64 ext_ident_word64_494,
                                  const SWord64 ext_ident_word64_495,
                                  const SWord64 ext_ident_word64_496,
                                  const SDouble ext_ident_double_505,
                                  const SWord64 ext_ident_word64_498,
                                  const SWord64 ext_ident_word64_499,
                                  const SWord64 ext_ident_word64_500,
                                  const SWord64 ext_ident_word64_501,
                                  const SWord64 ext_ident_word64_502,
                                  const SWord64 ext_ident_word64_503,
                                  const SWord64 ext_ident_word64_504)
{
  const SDouble s0 = ext_ident_double_497;
  const SWord64 s1 = ext_ident_word64_490;
  const SDouble s2 = ext_ownship_position_z;
  const SWord64 s3 = ext_ident_word64_491;
  const SWord64 s4 = ext_ident_word64_492;
  const SWord64 s5 = ext_ident_word64_493;
  const SWord64 s6 = ext_ident_word64_494;
  const SWord64 s7 = ext_ident_word64_495;
  const SWord64 s8 = ext_ident_word64_496;
  const SDouble s9 = ext_ident_double_505;
  const SWord64 s10 = ext_ident_word64_498;
  const SWord64 s11 = ext_ident_word64_499;
  const SWord64 s12 = ext_ident_word64_500;
  const SWord64 s13 = ext_ident_word64_501;
  const SWord64 s14 = ext_ident_word64_502;
  const SWord64 s15 = ext_ident_word64_503;
  const SWord64 s16 = ext_ident_word64_504;
  const SDouble s17 = s0 * s9;
  const SDouble s18 = s17 /* sq */;

  return s18;
}
