/* File: "ext_ident_double_295_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: mini",color=plum, style=filled]
0 -> 1
2 [label="op3: mux",color=green4, style=filled]
1 -> 2
3 [label="op2: <=",color=green4, style=filled]
2 -> 3
4 [label="ext_ident_double_226",color=cyan4, style=filled]
3 -> 4
648 [label="ext_ident_double_249",color=cyan4, style=filled]
3 -> 648
1307 [label="ext_ident_double_271",color=cyan4, style=filled]
2 -> 1307
1951 [label="ext_ident_double_294",color=cyan4, style=filled]
2 -> 1951


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((( (((ext_ident_double_226) <= (ext_ident_double_249))) ? (ext_ident_double_271) : (ext_ident_double_294))));
*/
SDouble ext_ident_double_295_arg0(const SDouble ext_ident_double_226,
                                  const SDouble ext_ident_double_205,
                                  const SDouble ext_ownship_position_x,
                                  const SDouble ext_intruder_position_x,
                                  const SDouble ext_ownship_velocity_x,
                                  const SDouble ext_intruder_velocity_x,
                                  const SDouble ext_ownship_position_y,
                                  const SDouble ext_intruder_position_y,
                                  const SDouble ext_ownship_velocity_y,
                                  const SDouble ext_intruder_velocity_y,
                                  const SDouble ext_ident_double_222,
                                  const SDouble ext_ident_double_213,
                                  const SWord64 ext_ident_word64_206,
                                  const SDouble ext_ownship_position_z,
                                  const SWord64 ext_ident_word64_207,
                                  const SWord64 ext_ident_word64_208,
                                  const SWord64 ext_ident_word64_209,
                                  const SWord64 ext_ident_word64_210,
                                  const SWord64 ext_ident_word64_211,
                                  const SWord64 ext_ident_word64_212,
                                  const SDouble ext_ident_double_221,
                                  const SWord64 ext_ident_word64_214,
                                  const SWord64 ext_ident_word64_215,
                                  const SWord64 ext_ident_word64_216,
                                  const SWord64 ext_ident_word64_217,
                                  const SWord64 ext_ident_word64_218,
                                  const SWord64 ext_ident_word64_219,
                                  const SWord64 ext_ident_word64_220,
                                  const SDouble ext_ident_double_224,
                                  const SDouble ext_ident_double_223,
                                  const SDouble ext_ident_double_225,
                                  const SDouble ext_ident_double_249,
                                  const SDouble ext_ident_double_248,
                                  const SDouble ext_ident_double_227,
                                  const SDouble ext_ident_double_244,
                                  const SDouble ext_ident_double_235,
                                  const SWord64 ext_ident_word64_228,
                                  const SWord64 ext_ident_word64_229,
                                  const SWord64 ext_ident_word64_230,
                                  const SWord64 ext_ident_word64_231,
                                  const SWord64 ext_ident_word64_232,
                                  const SWord64 ext_ident_word64_233,
                                  const SWord64 ext_ident_word64_234,
                                  const SDouble ext_ident_double_243,
                                  const SWord64 ext_ident_word64_236,
                                  const SWord64 ext_ident_word64_237,
                                  const SWord64 ext_ident_word64_238,
                                  const SWord64 ext_ident_word64_239,
                                  const SWord64 ext_ident_word64_240,
                                  const SWord64 ext_ident_word64_241,
                                  const SWord64 ext_ident_word64_242,
                                  const SDouble ext_ident_double_246,
                                  const SDouble ext_ident_double_245,
                                  const SDouble ext_ident_double_247,
                                  const SDouble ext_ownship_velocity_z,
                                  const SDouble ext_ident_double_271,
                                  const SDouble ext_ident_double_250,
                                  const SDouble ext_ident_double_267,
                                  const SDouble ext_ident_double_258,
                                  const SWord64 ext_ident_word64_251,
                                  const SWord64 ext_ident_word64_252,
                                  const SWord64 ext_ident_word64_253,
                                  const SWord64 ext_ident_word64_254,
                                  const SWord64 ext_ident_word64_255,
                                  const SWord64 ext_ident_word64_256,
                                  const SWord64 ext_ident_word64_257,
                                  const SDouble ext_ident_double_266,
                                  const SWord64 ext_ident_word64_259,
                                  const SWord64 ext_ident_word64_260,
                                  const SWord64 ext_ident_word64_261,
                                  const SWord64 ext_ident_word64_262,
                                  const SWord64 ext_ident_word64_263,
                                  const SWord64 ext_ident_word64_264,
                                  const SWord64 ext_ident_word64_265,
                                  const SDouble ext_ident_double_269,
                                  const SDouble ext_ident_double_268,
                                  const SDouble ext_ident_double_270,
                                  const SDouble ext_ident_double_294,
                                  const SDouble ext_ident_double_293,
                                  const SDouble ext_ident_double_272,
                                  const SDouble ext_ident_double_289,
                                  const SDouble ext_ident_double_280,
                                  const SWord64 ext_ident_word64_273,
                                  const SWord64 ext_ident_word64_274,
                                  const SWord64 ext_ident_word64_275,
                                  const SWord64 ext_ident_word64_276,
                                  const SWord64 ext_ident_word64_277,
                                  const SWord64 ext_ident_word64_278,
                                  const SWord64 ext_ident_word64_279,
                                  const SDouble ext_ident_double_288,
                                  const SWord64 ext_ident_word64_281,
                                  const SWord64 ext_ident_word64_282,
                                  const SWord64 ext_ident_word64_283,
                                  const SWord64 ext_ident_word64_284,
                                  const SWord64 ext_ident_word64_285,
                                  const SWord64 ext_ident_word64_286,
                                  const SWord64 ext_ident_word64_287,
                                  const SDouble ext_ident_double_291,
                                  const SDouble ext_ident_double_290,
                                  const SDouble ext_ident_double_292)
{
  const SDouble s0 = ext_ident_double_226;
  const SDouble s1 = ext_ident_double_205;
  const SDouble s2 = ext_ownship_position_x;
  const SDouble s3 = ext_intruder_position_x;
  const SDouble s4 = ext_ownship_velocity_x;
  const SDouble s5 = ext_intruder_velocity_x;
  const SDouble s6 = ext_ownship_position_y;
  const SDouble s7 = ext_intruder_position_y;
  const SDouble s8 = ext_ownship_velocity_y;
  const SDouble s9 = ext_intruder_velocity_y;
  const SDouble s10 = ext_ident_double_222;
  const SDouble s11 = ext_ident_double_213;
  const SWord64 s12 = ext_ident_word64_206;
  const SDouble s13 = ext_ownship_position_z;
  const SWord64 s14 = ext_ident_word64_207;
  const SWord64 s15 = ext_ident_word64_208;
  const SWord64 s16 = ext_ident_word64_209;
  const SWord64 s17 = ext_ident_word64_210;
  const SWord64 s18 = ext_ident_word64_211;
  const SWord64 s19 = ext_ident_word64_212;
  const SDouble s20 = ext_ident_double_221;
  const SWord64 s21 = ext_ident_word64_214;
  const SWord64 s22 = ext_ident_word64_215;
  const SWord64 s23 = ext_ident_word64_216;
  const SWord64 s24 = ext_ident_word64_217;
  const SWord64 s25 = ext_ident_word64_218;
  const SWord64 s26 = ext_ident_word64_219;
  const SWord64 s27 = ext_ident_word64_220;
  const SDouble s28 = ext_ident_double_224;
  const SDouble s29 = ext_ident_double_223;
  const SDouble s30 = ext_ident_double_225;
  const SDouble s31 = ext_ident_double_249;
  const SDouble s32 = ext_ident_double_248;
  const SDouble s33 = ext_ident_double_227;
  const SDouble s34 = ext_ident_double_244;
  const SDouble s35 = ext_ident_double_235;
  const SWord64 s36 = ext_ident_word64_228;
  const SWord64 s37 = ext_ident_word64_229;
  const SWord64 s38 = ext_ident_word64_230;
  const SWord64 s39 = ext_ident_word64_231;
  const SWord64 s40 = ext_ident_word64_232;
  const SWord64 s41 = ext_ident_word64_233;
  const SWord64 s42 = ext_ident_word64_234;
  const SDouble s43 = ext_ident_double_243;
  const SWord64 s44 = ext_ident_word64_236;
  const SWord64 s45 = ext_ident_word64_237;
  const SWord64 s46 = ext_ident_word64_238;
  const SWord64 s47 = ext_ident_word64_239;
  const SWord64 s48 = ext_ident_word64_240;
  const SWord64 s49 = ext_ident_word64_241;
  const SWord64 s50 = ext_ident_word64_242;
  const SDouble s51 = ext_ident_double_246;
  const SDouble s52 = ext_ident_double_245;
  const SDouble s53 = ext_ident_double_247;
  const SDouble s54 = ext_ownship_velocity_z;
  const SDouble s55 = ext_ident_double_271;
  const SDouble s56 = ext_ident_double_250;
  const SDouble s57 = ext_ident_double_267;
  const SDouble s58 = ext_ident_double_258;
  const SWord64 s59 = ext_ident_word64_251;
  const SWord64 s60 = ext_ident_word64_252;
  const SWord64 s61 = ext_ident_word64_253;
  const SWord64 s62 = ext_ident_word64_254;
  const SWord64 s63 = ext_ident_word64_255;
  const SWord64 s64 = ext_ident_word64_256;
  const SWord64 s65 = ext_ident_word64_257;
  const SDouble s66 = ext_ident_double_266;
  const SWord64 s67 = ext_ident_word64_259;
  const SWord64 s68 = ext_ident_word64_260;
  const SWord64 s69 = ext_ident_word64_261;
  const SWord64 s70 = ext_ident_word64_262;
  const SWord64 s71 = ext_ident_word64_263;
  const SWord64 s72 = ext_ident_word64_264;
  const SWord64 s73 = ext_ident_word64_265;
  const SDouble s74 = ext_ident_double_269;
  const SDouble s75 = ext_ident_double_268;
  const SDouble s76 = ext_ident_double_270;
  const SDouble s77 = ext_ident_double_294;
  const SDouble s78 = ext_ident_double_293;
  const SDouble s79 = ext_ident_double_272;
  const SDouble s80 = ext_ident_double_289;
  const SDouble s81 = ext_ident_double_280;
  const SWord64 s82 = ext_ident_word64_273;
  const SWord64 s83 = ext_ident_word64_274;
  const SWord64 s84 = ext_ident_word64_275;
  const SWord64 s85 = ext_ident_word64_276;
  const SWord64 s86 = ext_ident_word64_277;
  const SWord64 s87 = ext_ident_word64_278;
  const SWord64 s88 = ext_ident_word64_279;
  const SDouble s89 = ext_ident_double_288;
  const SWord64 s90 = ext_ident_word64_281;
  const SWord64 s91 = ext_ident_word64_282;
  const SWord64 s92 = ext_ident_word64_283;
  const SWord64 s93 = ext_ident_word64_284;
  const SWord64 s94 = ext_ident_word64_285;
  const SWord64 s95 = ext_ident_word64_286;
  const SWord64 s96 = ext_ident_word64_287;
  const SDouble s97 = ext_ident_double_291;
  const SDouble s98 = ext_ident_double_290;
  const SDouble s99 = ext_ident_double_292;
  const SBool   s100 = s0 <= s31;
  const SDouble s101 = s100 ? s55 : s77;
  const SDouble s102 = s101 /* mini */;

  return s102;
}
