/* File: "ext_ident_double_202_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: mini",color=plum, style=filled]
0 -> 1
2 [label="op3: mux",color=green4, style=filled]
1 -> 2
3 [label="op2: <=",color=green4, style=filled]
2 -> 3
4 [label="ext_ident_double_133",color=cyan4, style=filled]
3 -> 4
648 [label="ext_ident_double_156",color=cyan4, style=filled]
3 -> 648
1307 [label="ext_ident_double_178",color=cyan4, style=filled]
2 -> 1307
1951 [label="ext_ident_double_201",color=cyan4, style=filled]
2 -> 1951


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((( (((ext_ident_double_133) <= (ext_ident_double_156))) ? (ext_ident_double_178) : (ext_ident_double_201))));
*/
SDouble ext_ident_double_202_arg0(const SDouble ext_ident_double_133,
                                  const SDouble ext_ident_double_112,
                                  const SDouble ext_ownship_position_x,
                                  const SDouble ext_intruder_position_x,
                                  const SDouble ext_ownship_velocity_x,
                                  const SDouble ext_intruder_velocity_x,
                                  const SDouble ext_ownship_position_y,
                                  const SDouble ext_intruder_position_y,
                                  const SDouble ext_ownship_velocity_y,
                                  const SDouble ext_intruder_velocity_y,
                                  const SDouble ext_ident_double_129,
                                  const SDouble ext_ident_double_120,
                                  const SWord64 ext_ident_word64_113,
                                  const SDouble ext_ownship_position_z,
                                  const SWord64 ext_ident_word64_114,
                                  const SWord64 ext_ident_word64_115,
                                  const SWord64 ext_ident_word64_116,
                                  const SWord64 ext_ident_word64_117,
                                  const SWord64 ext_ident_word64_118,
                                  const SWord64 ext_ident_word64_119,
                                  const SDouble ext_ident_double_128,
                                  const SWord64 ext_ident_word64_121,
                                  const SWord64 ext_ident_word64_122,
                                  const SWord64 ext_ident_word64_123,
                                  const SWord64 ext_ident_word64_124,
                                  const SWord64 ext_ident_word64_125,
                                  const SWord64 ext_ident_word64_126,
                                  const SWord64 ext_ident_word64_127,
                                  const SDouble ext_ident_double_131,
                                  const SDouble ext_ident_double_130,
                                  const SDouble ext_ident_double_132,
                                  const SDouble ext_ident_double_156,
                                  const SDouble ext_ident_double_155,
                                  const SDouble ext_ident_double_134,
                                  const SDouble ext_ident_double_151,
                                  const SDouble ext_ident_double_142,
                                  const SWord64 ext_ident_word64_135,
                                  const SWord64 ext_ident_word64_136,
                                  const SWord64 ext_ident_word64_137,
                                  const SWord64 ext_ident_word64_138,
                                  const SWord64 ext_ident_word64_139,
                                  const SWord64 ext_ident_word64_140,
                                  const SWord64 ext_ident_word64_141,
                                  const SDouble ext_ident_double_150,
                                  const SWord64 ext_ident_word64_143,
                                  const SWord64 ext_ident_word64_144,
                                  const SWord64 ext_ident_word64_145,
                                  const SWord64 ext_ident_word64_146,
                                  const SWord64 ext_ident_word64_147,
                                  const SWord64 ext_ident_word64_148,
                                  const SWord64 ext_ident_word64_149,
                                  const SDouble ext_ident_double_153,
                                  const SDouble ext_ident_double_152,
                                  const SDouble ext_ident_double_154,
                                  const SDouble ext_ownship_velocity_z,
                                  const SDouble ext_ident_double_178,
                                  const SDouble ext_ident_double_157,
                                  const SDouble ext_ident_double_174,
                                  const SDouble ext_ident_double_165,
                                  const SWord64 ext_ident_word64_158,
                                  const SWord64 ext_ident_word64_159,
                                  const SWord64 ext_ident_word64_160,
                                  const SWord64 ext_ident_word64_161,
                                  const SWord64 ext_ident_word64_162,
                                  const SWord64 ext_ident_word64_163,
                                  const SWord64 ext_ident_word64_164,
                                  const SDouble ext_ident_double_173,
                                  const SWord64 ext_ident_word64_166,
                                  const SWord64 ext_ident_word64_167,
                                  const SWord64 ext_ident_word64_168,
                                  const SWord64 ext_ident_word64_169,
                                  const SWord64 ext_ident_word64_170,
                                  const SWord64 ext_ident_word64_171,
                                  const SWord64 ext_ident_word64_172,
                                  const SDouble ext_ident_double_176,
                                  const SDouble ext_ident_double_175,
                                  const SDouble ext_ident_double_177,
                                  const SDouble ext_ident_double_201,
                                  const SDouble ext_ident_double_200,
                                  const SDouble ext_ident_double_179,
                                  const SDouble ext_ident_double_196,
                                  const SDouble ext_ident_double_187,
                                  const SWord64 ext_ident_word64_180,
                                  const SWord64 ext_ident_word64_181,
                                  const SWord64 ext_ident_word64_182,
                                  const SWord64 ext_ident_word64_183,
                                  const SWord64 ext_ident_word64_184,
                                  const SWord64 ext_ident_word64_185,
                                  const SWord64 ext_ident_word64_186,
                                  const SDouble ext_ident_double_195,
                                  const SWord64 ext_ident_word64_188,
                                  const SWord64 ext_ident_word64_189,
                                  const SWord64 ext_ident_word64_190,
                                  const SWord64 ext_ident_word64_191,
                                  const SWord64 ext_ident_word64_192,
                                  const SWord64 ext_ident_word64_193,
                                  const SWord64 ext_ident_word64_194,
                                  const SDouble ext_ident_double_198,
                                  const SDouble ext_ident_double_197,
                                  const SDouble ext_ident_double_199)
{
  const SDouble s0 = ext_ident_double_133;
  const SDouble s1 = ext_ident_double_112;
  const SDouble s2 = ext_ownship_position_x;
  const SDouble s3 = ext_intruder_position_x;
  const SDouble s4 = ext_ownship_velocity_x;
  const SDouble s5 = ext_intruder_velocity_x;
  const SDouble s6 = ext_ownship_position_y;
  const SDouble s7 = ext_intruder_position_y;
  const SDouble s8 = ext_ownship_velocity_y;
  const SDouble s9 = ext_intruder_velocity_y;
  const SDouble s10 = ext_ident_double_129;
  const SDouble s11 = ext_ident_double_120;
  const SWord64 s12 = ext_ident_word64_113;
  const SDouble s13 = ext_ownship_position_z;
  const SWord64 s14 = ext_ident_word64_114;
  const SWord64 s15 = ext_ident_word64_115;
  const SWord64 s16 = ext_ident_word64_116;
  const SWord64 s17 = ext_ident_word64_117;
  const SWord64 s18 = ext_ident_word64_118;
  const SWord64 s19 = ext_ident_word64_119;
  const SDouble s20 = ext_ident_double_128;
  const SWord64 s21 = ext_ident_word64_121;
  const SWord64 s22 = ext_ident_word64_122;
  const SWord64 s23 = ext_ident_word64_123;
  const SWord64 s24 = ext_ident_word64_124;
  const SWord64 s25 = ext_ident_word64_125;
  const SWord64 s26 = ext_ident_word64_126;
  const SWord64 s27 = ext_ident_word64_127;
  const SDouble s28 = ext_ident_double_131;
  const SDouble s29 = ext_ident_double_130;
  const SDouble s30 = ext_ident_double_132;
  const SDouble s31 = ext_ident_double_156;
  const SDouble s32 = ext_ident_double_155;
  const SDouble s33 = ext_ident_double_134;
  const SDouble s34 = ext_ident_double_151;
  const SDouble s35 = ext_ident_double_142;
  const SWord64 s36 = ext_ident_word64_135;
  const SWord64 s37 = ext_ident_word64_136;
  const SWord64 s38 = ext_ident_word64_137;
  const SWord64 s39 = ext_ident_word64_138;
  const SWord64 s40 = ext_ident_word64_139;
  const SWord64 s41 = ext_ident_word64_140;
  const SWord64 s42 = ext_ident_word64_141;
  const SDouble s43 = ext_ident_double_150;
  const SWord64 s44 = ext_ident_word64_143;
  const SWord64 s45 = ext_ident_word64_144;
  const SWord64 s46 = ext_ident_word64_145;
  const SWord64 s47 = ext_ident_word64_146;
  const SWord64 s48 = ext_ident_word64_147;
  const SWord64 s49 = ext_ident_word64_148;
  const SWord64 s50 = ext_ident_word64_149;
  const SDouble s51 = ext_ident_double_153;
  const SDouble s52 = ext_ident_double_152;
  const SDouble s53 = ext_ident_double_154;
  const SDouble s54 = ext_ownship_velocity_z;
  const SDouble s55 = ext_ident_double_178;
  const SDouble s56 = ext_ident_double_157;
  const SDouble s57 = ext_ident_double_174;
  const SDouble s58 = ext_ident_double_165;
  const SWord64 s59 = ext_ident_word64_158;
  const SWord64 s60 = ext_ident_word64_159;
  const SWord64 s61 = ext_ident_word64_160;
  const SWord64 s62 = ext_ident_word64_161;
  const SWord64 s63 = ext_ident_word64_162;
  const SWord64 s64 = ext_ident_word64_163;
  const SWord64 s65 = ext_ident_word64_164;
  const SDouble s66 = ext_ident_double_173;
  const SWord64 s67 = ext_ident_word64_166;
  const SWord64 s68 = ext_ident_word64_167;
  const SWord64 s69 = ext_ident_word64_168;
  const SWord64 s70 = ext_ident_word64_169;
  const SWord64 s71 = ext_ident_word64_170;
  const SWord64 s72 = ext_ident_word64_171;
  const SWord64 s73 = ext_ident_word64_172;
  const SDouble s74 = ext_ident_double_176;
  const SDouble s75 = ext_ident_double_175;
  const SDouble s76 = ext_ident_double_177;
  const SDouble s77 = ext_ident_double_201;
  const SDouble s78 = ext_ident_double_200;
  const SDouble s79 = ext_ident_double_179;
  const SDouble s80 = ext_ident_double_196;
  const SDouble s81 = ext_ident_double_187;
  const SWord64 s82 = ext_ident_word64_180;
  const SWord64 s83 = ext_ident_word64_181;
  const SWord64 s84 = ext_ident_word64_182;
  const SWord64 s85 = ext_ident_word64_183;
  const SWord64 s86 = ext_ident_word64_184;
  const SWord64 s87 = ext_ident_word64_185;
  const SWord64 s88 = ext_ident_word64_186;
  const SDouble s89 = ext_ident_double_195;
  const SWord64 s90 = ext_ident_word64_188;
  const SWord64 s91 = ext_ident_word64_189;
  const SWord64 s92 = ext_ident_word64_190;
  const SWord64 s93 = ext_ident_word64_191;
  const SWord64 s94 = ext_ident_word64_192;
  const SWord64 s95 = ext_ident_word64_193;
  const SWord64 s96 = ext_ident_word64_194;
  const SDouble s97 = ext_ident_double_198;
  const SDouble s98 = ext_ident_double_197;
  const SDouble s99 = ext_ident_double_199;
  const SBool   s100 = s0 <= s31;
  const SDouble s101 = s100 ? s55 : s77;
  const SDouble s102 = s101 /* mini */;

  return s102;
}
