/* File: "ext_ident_double_813_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: down_dist",color=plum, style=filled]
0 -> 1
2 [label="op2: -",color=green4, style=filled]
1 -> 2
3 [label="ext_ident_double_443",color=cyan4, style=filled]
2 -> 3
653 [label="ext_ident_double_812",color=cyan4, style=filled]
2 -> 653


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((ext_ident_double_443) - (ext_ident_double_812))));
*/
SDouble ext_ident_double_813_arg0(const SDouble ext_ident_double_443,
                                  const SDouble ext_intruder_position_z,
                                  const SDouble ext_ident_double_442,
                                  const SDouble ext_ident_double_421,
                                  const SDouble ext_ownship_position_x,
                                  const SDouble ext_intruder_position_x,
                                  const SDouble ext_ownship_velocity_x,
                                  const SDouble ext_intruder_velocity_x,
                                  const SDouble ext_ownship_position_y,
                                  const SDouble ext_intruder_position_y,
                                  const SDouble ext_ownship_velocity_y,
                                  const SDouble ext_intruder_velocity_y,
                                  const SDouble ext_ident_double_438,
                                  const SDouble ext_ident_double_429,
                                  const SWord64 ext_ident_word64_422,
                                  const SDouble ext_ownship_position_z,
                                  const SWord64 ext_ident_word64_423,
                                  const SWord64 ext_ident_word64_424,
                                  const SWord64 ext_ident_word64_425,
                                  const SWord64 ext_ident_word64_426,
                                  const SWord64 ext_ident_word64_427,
                                  const SWord64 ext_ident_word64_428,
                                  const SDouble ext_ident_double_437,
                                  const SWord64 ext_ident_word64_430,
                                  const SWord64 ext_ident_word64_431,
                                  const SWord64 ext_ident_word64_432,
                                  const SWord64 ext_ident_word64_433,
                                  const SWord64 ext_ident_word64_434,
                                  const SWord64 ext_ident_word64_435,
                                  const SWord64 ext_ident_word64_436,
                                  const SDouble ext_ident_double_440,
                                  const SDouble ext_ident_double_439,
                                  const SDouble ext_ident_double_441,
                                  const SDouble ext_intruder_velocity_z,
                                  const SDouble ext_ident_double_812,
                                  const SDouble ext_ident_double_628,
                                  const SDouble ext_ident_double_535,
                                  const SDouble ext_ident_double_534,
                                  const SDouble ext_ident_double_465,
                                  const SDouble ext_ident_double_444,
                                  const SDouble ext_ident_double_461,
                                  const SDouble ext_ident_double_452,
                                  const SWord64 ext_ident_word64_445,
                                  const SWord64 ext_ident_word64_446,
                                  const SWord64 ext_ident_word64_447,
                                  const SWord64 ext_ident_word64_448,
                                  const SWord64 ext_ident_word64_449,
                                  const SWord64 ext_ident_word64_450,
                                  const SWord64 ext_ident_word64_451,
                                  const SDouble ext_ident_double_460,
                                  const SWord64 ext_ident_word64_453,
                                  const SWord64 ext_ident_word64_454,
                                  const SWord64 ext_ident_word64_455,
                                  const SWord64 ext_ident_word64_456,
                                  const SWord64 ext_ident_word64_457,
                                  const SWord64 ext_ident_word64_458,
                                  const SWord64 ext_ident_word64_459,
                                  const SDouble ext_ident_double_463,
                                  const SDouble ext_ident_double_462,
                                  const SDouble ext_ident_double_464,
                                  const SDouble ext_ident_double_488,
                                  const SDouble ext_ident_double_487,
                                  const SDouble ext_ident_double_466,
                                  const SDouble ext_ident_double_483,
                                  const SDouble ext_ident_double_474,
                                  const SWord64 ext_ident_word64_467,
                                  const SWord64 ext_ident_word64_468,
                                  const SWord64 ext_ident_word64_469,
                                  const SWord64 ext_ident_word64_470,
                                  const SWord64 ext_ident_word64_471,
                                  const SWord64 ext_ident_word64_472,
                                  const SWord64 ext_ident_word64_473,
                                  const SDouble ext_ident_double_482,
                                  const SWord64 ext_ident_word64_475,
                                  const SWord64 ext_ident_word64_476,
                                  const SWord64 ext_ident_word64_477,
                                  const SWord64 ext_ident_word64_478,
                                  const SWord64 ext_ident_word64_479,
                                  const SWord64 ext_ident_word64_480,
                                  const SWord64 ext_ident_word64_481,
                                  const SDouble ext_ident_double_485,
                                  const SDouble ext_ident_double_484,
                                  const SDouble ext_ident_double_486,
                                  const SDouble ext_ownship_velocity_z,
                                  const SDouble ext_ident_double_510,
                                  const SDouble ext_ident_double_489,
                                  const SDouble ext_ident_double_506,
                                  const SDouble ext_ident_double_497,
                                  const SWord64 ext_ident_word64_490,
                                  const SWord64 ext_ident_word64_491,
                                  const SWord64 ext_ident_word64_492,
                                  const SWord64 ext_ident_word64_493,
                                  const SWord64 ext_ident_word64_494,
                                  const SWord64 ext_ident_word64_495,
                                  const SWord64 ext_ident_word64_496,
                                  const SDouble ext_ident_double_505,
                                  const SWord64 ext_ident_word64_498,
                                  const SWord64 ext_ident_word64_499,
                                  const SWord64 ext_ident_word64_500,
                                  const SWord64 ext_ident_word64_501,
                                  const SWord64 ext_ident_word64_502,
                                  const SWord64 ext_ident_word64_503,
                                  const SWord64 ext_ident_word64_504,
                                  const SDouble ext_ident_double_508,
                                  const SDouble ext_ident_double_507,
                                  const SDouble ext_ident_double_509,
                                  const SDouble ext_ident_double_533,
                                  const SDouble ext_ident_double_532,
                                  const SDouble ext_ident_double_511,
                                  const SDouble ext_ident_double_528,
                                  const SDouble ext_ident_double_519,
                                  const SWord64 ext_ident_word64_512,
                                  const SWord64 ext_ident_word64_513,
                                  const SWord64 ext_ident_word64_514,
                                  const SWord64 ext_ident_word64_515,
                                  const SWord64 ext_ident_word64_516,
                                  const SWord64 ext_ident_word64_517,
                                  const SWord64 ext_ident_word64_518,
                                  const SDouble ext_ident_double_527,
                                  const SWord64 ext_ident_word64_520,
                                  const SWord64 ext_ident_word64_521,
                                  const SWord64 ext_ident_word64_522,
                                  const SWord64 ext_ident_word64_523,
                                  const SWord64 ext_ident_word64_524,
                                  const SWord64 ext_ident_word64_525,
                                  const SWord64 ext_ident_word64_526,
                                  const SDouble ext_ident_double_530,
                                  const SDouble ext_ident_double_529,
                                  const SDouble ext_ident_double_531,
                                  const SDouble ext_ident_double_627,
                                  const SDouble ext_ident_double_626,
                                  const SDouble ext_ident_double_557,
                                  const SDouble ext_ident_double_536,
                                  const SDouble ext_ident_double_553,
                                  const SDouble ext_ident_double_544,
                                  const SWord64 ext_ident_word64_537,
                                  const SWord64 ext_ident_word64_538,
                                  const SWord64 ext_ident_word64_539,
                                  const SWord64 ext_ident_word64_540,
                                  const SWord64 ext_ident_word64_541,
                                  const SWord64 ext_ident_word64_542,
                                  const SWord64 ext_ident_word64_543,
                                  const SDouble ext_ident_double_552,
                                  const SWord64 ext_ident_word64_545,
                                  const SWord64 ext_ident_word64_546,
                                  const SWord64 ext_ident_word64_547,
                                  const SWord64 ext_ident_word64_548,
                                  const SWord64 ext_ident_word64_549,
                                  const SWord64 ext_ident_word64_550,
                                  const SWord64 ext_ident_word64_551,
                                  const SDouble ext_ident_double_555,
                                  const SDouble ext_ident_double_554,
                                  const SDouble ext_ident_double_556,
                                  const SDouble ext_ident_double_580,
                                  const SDouble ext_ident_double_579,
                                  const SDouble ext_ident_double_558,
                                  const SDouble ext_ident_double_575,
                                  const SDouble ext_ident_double_566,
                                  const SWord64 ext_ident_word64_559,
                                  const SWord64 ext_ident_word64_560,
                                  const SWord64 ext_ident_word64_561,
                                  const SWord64 ext_ident_word64_562,
                                  const SWord64 ext_ident_word64_563,
                                  const SWord64 ext_ident_word64_564,
                                  const SWord64 ext_ident_word64_565,
                                  const SDouble ext_ident_double_574,
                                  const SWord64 ext_ident_word64_567,
                                  const SWord64 ext_ident_word64_568,
                                  const SWord64 ext_ident_word64_569,
                                  const SWord64 ext_ident_word64_570,
                                  const SWord64 ext_ident_word64_571,
                                  const SWord64 ext_ident_word64_572,
                                  const SWord64 ext_ident_word64_573,
                                  const SDouble ext_ident_double_577,
                                  const SDouble ext_ident_double_576,
                                  const SDouble ext_ident_double_578,
                                  const SDouble ext_ident_double_602,
                                  const SDouble ext_ident_double_581,
                                  const SDouble ext_ident_double_598,
                                  const SDouble ext_ident_double_589,
                                  const SWord64 ext_ident_word64_582,
                                  const SWord64 ext_ident_word64_583,
                                  const SWord64 ext_ident_word64_584,
                                  const SWord64 ext_ident_word64_585,
                                  const SWord64 ext_ident_word64_586,
                                  const SWord64 ext_ident_word64_587,
                                  const SWord64 ext_ident_word64_588,
                                  const SDouble ext_ident_double_597,
                                  const SWord64 ext_ident_word64_590,
                                  const SWord64 ext_ident_word64_591,
                                  const SWord64 ext_ident_word64_592,
                                  const SWord64 ext_ident_word64_593,
                                  const SWord64 ext_ident_word64_594,
                                  const SWord64 ext_ident_word64_595,
                                  const SWord64 ext_ident_word64_596,
                                  const SDouble ext_ident_double_600,
                                  const SDouble ext_ident_double_599,
                                  const SDouble ext_ident_double_601,
                                  const SDouble ext_ident_double_625,
                                  const SDouble ext_ident_double_624,
                                  const SDouble ext_ident_double_603,
                                  const SDouble ext_ident_double_620,
                                  const SDouble ext_ident_double_611,
                                  const SWord64 ext_ident_word64_604,
                                  const SWord64 ext_ident_word64_605,
                                  const SWord64 ext_ident_word64_606,
                                  const SWord64 ext_ident_word64_607,
                                  const SWord64 ext_ident_word64_608,
                                  const SWord64 ext_ident_word64_609,
                                  const SWord64 ext_ident_word64_610,
                                  const SDouble ext_ident_double_619,
                                  const SWord64 ext_ident_word64_612,
                                  const SWord64 ext_ident_word64_613,
                                  const SWord64 ext_ident_word64_614,
                                  const SWord64 ext_ident_word64_615,
                                  const SWord64 ext_ident_word64_616,
                                  const SWord64 ext_ident_word64_617,
                                  const SWord64 ext_ident_word64_618,
                                  const SDouble ext_ident_double_622,
                                  const SDouble ext_ident_double_621,
                                  const SDouble ext_ident_double_623,
                                  const SDouble ext_ident_double_720,
                                  const SDouble ext_ident_double_719,
                                  const SDouble ext_ident_double_650,
                                  const SDouble ext_ident_double_629,
                                  const SDouble ext_ident_double_646,
                                  const SDouble ext_ident_double_637,
                                  const SWord64 ext_ident_word64_630,
                                  const SWord64 ext_ident_word64_631,
                                  const SWord64 ext_ident_word64_632,
                                  const SWord64 ext_ident_word64_633,
                                  const SWord64 ext_ident_word64_634,
                                  const SWord64 ext_ident_word64_635,
                                  const SWord64 ext_ident_word64_636,
                                  const SDouble ext_ident_double_645,
                                  const SWord64 ext_ident_word64_638,
                                  const SWord64 ext_ident_word64_639,
                                  const SWord64 ext_ident_word64_640,
                                  const SWord64 ext_ident_word64_641,
                                  const SWord64 ext_ident_word64_642,
                                  const SWord64 ext_ident_word64_643,
                                  const SWord64 ext_ident_word64_644,
                                  const SDouble ext_ident_double_648,
                                  const SDouble ext_ident_double_647,
                                  const SDouble ext_ident_double_649,
                                  const SDouble ext_ident_double_673,
                                  const SDouble ext_ident_double_672,
                                  const SDouble ext_ident_double_651,
                                  const SDouble ext_ident_double_668,
                                  const SDouble ext_ident_double_659,
                                  const SWord64 ext_ident_word64_652,
                                  const SWord64 ext_ident_word64_653,
                                  const SWord64 ext_ident_word64_654,
                                  const SWord64 ext_ident_word64_655,
                                  const SWord64 ext_ident_word64_656,
                                  const SWord64 ext_ident_word64_657,
                                  const SWord64 ext_ident_word64_658,
                                  const SDouble ext_ident_double_667,
                                  const SWord64 ext_ident_word64_660,
                                  const SWord64 ext_ident_word64_661,
                                  const SWord64 ext_ident_word64_662,
                                  const SWord64 ext_ident_word64_663,
                                  const SWord64 ext_ident_word64_664,
                                  const SWord64 ext_ident_word64_665,
                                  const SWord64 ext_ident_word64_666,
                                  const SDouble ext_ident_double_670,
                                  const SDouble ext_ident_double_669,
                                  const SDouble ext_ident_double_671,
                                  const SDouble ext_ident_double_695,
                                  const SDouble ext_ident_double_674,
                                  const SDouble ext_ident_double_691,
                                  const SDouble ext_ident_double_682,
                                  const SWord64 ext_ident_word64_675,
                                  const SWord64 ext_ident_word64_676,
                                  const SWord64 ext_ident_word64_677,
                                  const SWord64 ext_ident_word64_678,
                                  const SWord64 ext_ident_word64_679,
                                  const SWord64 ext_ident_word64_680,
                                  const SWord64 ext_ident_word64_681,
                                  const SDouble ext_ident_double_690,
                                  const SWord64 ext_ident_word64_683,
                                  const SWord64 ext_ident_word64_684,
                                  const SWord64 ext_ident_word64_685,
                                  const SWord64 ext_ident_word64_686,
                                  const SWord64 ext_ident_word64_687,
                                  const SWord64 ext_ident_word64_688,
                                  const SWord64 ext_ident_word64_689,
                                  const SDouble ext_ident_double_693,
                                  const SDouble ext_ident_double_692,
                                  const SDouble ext_ident_double_694,
                                  const SDouble ext_ident_double_718,
                                  const SDouble ext_ident_double_717,
                                  const SDouble ext_ident_double_696,
                                  const SDouble ext_ident_double_713,
                                  const SDouble ext_ident_double_704,
                                  const SWord64 ext_ident_word64_697,
                                  const SWord64 ext_ident_word64_698,
                                  const SWord64 ext_ident_word64_699,
                                  const SWord64 ext_ident_word64_700,
                                  const SWord64 ext_ident_word64_701,
                                  const SWord64 ext_ident_word64_702,
                                  const SWord64 ext_ident_word64_703,
                                  const SDouble ext_ident_double_712,
                                  const SWord64 ext_ident_word64_705,
                                  const SWord64 ext_ident_word64_706,
                                  const SWord64 ext_ident_word64_707,
                                  const SWord64 ext_ident_word64_708,
                                  const SWord64 ext_ident_word64_709,
                                  const SWord64 ext_ident_word64_710,
                                  const SWord64 ext_ident_word64_711,
                                  const SDouble ext_ident_double_715,
                                  const SDouble ext_ident_double_714,
                                  const SDouble ext_ident_double_716,
                                  const SDouble ext_ident_double_811,
                                  const SDouble ext_ident_double_742,
                                  const SDouble ext_ident_double_721,
                                  const SDouble ext_ident_double_738,
                                  const SDouble ext_ident_double_729,
                                  const SWord64 ext_ident_word64_722,
                                  const SWord64 ext_ident_word64_723,
                                  const SWord64 ext_ident_word64_724,
                                  const SWord64 ext_ident_word64_725,
                                  const SWord64 ext_ident_word64_726,
                                  const SWord64 ext_ident_word64_727,
                                  const SWord64 ext_ident_word64_728,
                                  const SDouble ext_ident_double_737,
                                  const SWord64 ext_ident_word64_730,
                                  const SWord64 ext_ident_word64_731,
                                  const SWord64 ext_ident_word64_732,
                                  const SWord64 ext_ident_word64_733,
                                  const SWord64 ext_ident_word64_734,
                                  const SWord64 ext_ident_word64_735,
                                  const SWord64 ext_ident_word64_736,
                                  const SDouble ext_ident_double_740,
                                  const SDouble ext_ident_double_739,
                                  const SDouble ext_ident_double_741,
                                  const SDouble ext_ident_double_765,
                                  const SDouble ext_ident_double_764,
                                  const SDouble ext_ident_double_743,
                                  const SDouble ext_ident_double_760,
                                  const SDouble ext_ident_double_751,
                                  const SWord64 ext_ident_word64_744,
                                  const SWord64 ext_ident_word64_745,
                                  const SWord64 ext_ident_word64_746,
                                  const SWord64 ext_ident_word64_747,
                                  const SWord64 ext_ident_word64_748,
                                  const SWord64 ext_ident_word64_749,
                                  const SWord64 ext_ident_word64_750,
                                  const SDouble ext_ident_double_759,
                                  const SWord64 ext_ident_word64_752,
                                  const SWord64 ext_ident_word64_753,
                                  const SWord64 ext_ident_word64_754,
                                  const SWord64 ext_ident_word64_755,
                                  const SWord64 ext_ident_word64_756,
                                  const SWord64 ext_ident_word64_757,
                                  const SWord64 ext_ident_word64_758,
                                  const SDouble ext_ident_double_762,
                                  const SDouble ext_ident_double_761,
                                  const SDouble ext_ident_double_763,
                                  const SDouble ext_ident_double_787,
                                  const SDouble ext_ident_double_766,
                                  const SDouble ext_ident_double_783,
                                  const SDouble ext_ident_double_774,
                                  const SWord64 ext_ident_word64_767,
                                  const SWord64 ext_ident_word64_768,
                                  const SWord64 ext_ident_word64_769,
                                  const SWord64 ext_ident_word64_770,
                                  const SWord64 ext_ident_word64_771,
                                  const SWord64 ext_ident_word64_772,
                                  const SWord64 ext_ident_word64_773,
                                  const SDouble ext_ident_double_782,
                                  const SWord64 ext_ident_word64_775,
                                  const SWord64 ext_ident_word64_776,
                                  const SWord64 ext_ident_word64_777,
                                  const SWord64 ext_ident_word64_778,
                                  const SWord64 ext_ident_word64_779,
                                  const SWord64 ext_ident_word64_780,
                                  const SWord64 ext_ident_word64_781,
                                  const SDouble ext_ident_double_785,
                                  const SDouble ext_ident_double_784,
                                  const SDouble ext_ident_double_786,
                                  const SDouble ext_ident_double_810,
                                  const SDouble ext_ident_double_809,
                                  const SDouble ext_ident_double_788,
                                  const SDouble ext_ident_double_805,
                                  const SDouble ext_ident_double_796,
                                  const SWord64 ext_ident_word64_789,
                                  const SWord64 ext_ident_word64_790,
                                  const SWord64 ext_ident_word64_791,
                                  const SWord64 ext_ident_word64_792,
                                  const SWord64 ext_ident_word64_793,
                                  const SWord64 ext_ident_word64_794,
                                  const SWord64 ext_ident_word64_795,
                                  const SDouble ext_ident_double_804,
                                  const SWord64 ext_ident_word64_797,
                                  const SWord64 ext_ident_word64_798,
                                  const SWord64 ext_ident_word64_799,
                                  const SWord64 ext_ident_word64_800,
                                  const SWord64 ext_ident_word64_801,
                                  const SWord64 ext_ident_word64_802,
                                  const SWord64 ext_ident_word64_803,
                                  const SDouble ext_ident_double_807,
                                  const SDouble ext_ident_double_806,
                                  const SDouble ext_ident_double_808)
{
  const SDouble s0 = ext_ident_double_443;
  const SDouble s1 = ext_intruder_position_z;
  const SDouble s2 = ext_ident_double_442;
  const SDouble s3 = ext_ident_double_421;
  const SDouble s4 = ext_ownship_position_x;
  const SDouble s5 = ext_intruder_position_x;
  const SDouble s6 = ext_ownship_velocity_x;
  const SDouble s7 = ext_intruder_velocity_x;
  const SDouble s8 = ext_ownship_position_y;
  const SDouble s9 = ext_intruder_position_y;
  const SDouble s10 = ext_ownship_velocity_y;
  const SDouble s11 = ext_intruder_velocity_y;
  const SDouble s12 = ext_ident_double_438;
  const SDouble s13 = ext_ident_double_429;
  const SWord64 s14 = ext_ident_word64_422;
  const SDouble s15 = ext_ownship_position_z;
  const SWord64 s16 = ext_ident_word64_423;
  const SWord64 s17 = ext_ident_word64_424;
  const SWord64 s18 = ext_ident_word64_425;
  const SWord64 s19 = ext_ident_word64_426;
  const SWord64 s20 = ext_ident_word64_427;
  const SWord64 s21 = ext_ident_word64_428;
  const SDouble s22 = ext_ident_double_437;
  const SWord64 s23 = ext_ident_word64_430;
  const SWord64 s24 = ext_ident_word64_431;
  const SWord64 s25 = ext_ident_word64_432;
  const SWord64 s26 = ext_ident_word64_433;
  const SWord64 s27 = ext_ident_word64_434;
  const SWord64 s28 = ext_ident_word64_435;
  const SWord64 s29 = ext_ident_word64_436;
  const SDouble s30 = ext_ident_double_440;
  const SDouble s31 = ext_ident_double_439;
  const SDouble s32 = ext_ident_double_441;
  const SDouble s33 = ext_intruder_velocity_z;
  const SDouble s34 = ext_ident_double_812;
  const SDouble s35 = ext_ident_double_628;
  const SDouble s36 = ext_ident_double_535;
  const SDouble s37 = ext_ident_double_534;
  const SDouble s38 = ext_ident_double_465;
  const SDouble s39 = ext_ident_double_444;
  const SDouble s40 = ext_ident_double_461;
  const SDouble s41 = ext_ident_double_452;
  const SWord64 s42 = ext_ident_word64_445;
  const SWord64 s43 = ext_ident_word64_446;
  const SWord64 s44 = ext_ident_word64_447;
  const SWord64 s45 = ext_ident_word64_448;
  const SWord64 s46 = ext_ident_word64_449;
  const SWord64 s47 = ext_ident_word64_450;
  const SWord64 s48 = ext_ident_word64_451;
  const SDouble s49 = ext_ident_double_460;
  const SWord64 s50 = ext_ident_word64_453;
  const SWord64 s51 = ext_ident_word64_454;
  const SWord64 s52 = ext_ident_word64_455;
  const SWord64 s53 = ext_ident_word64_456;
  const SWord64 s54 = ext_ident_word64_457;
  const SWord64 s55 = ext_ident_word64_458;
  const SWord64 s56 = ext_ident_word64_459;
  const SDouble s57 = ext_ident_double_463;
  const SDouble s58 = ext_ident_double_462;
  const SDouble s59 = ext_ident_double_464;
  const SDouble s60 = ext_ident_double_488;
  const SDouble s61 = ext_ident_double_487;
  const SDouble s62 = ext_ident_double_466;
  const SDouble s63 = ext_ident_double_483;
  const SDouble s64 = ext_ident_double_474;
  const SWord64 s65 = ext_ident_word64_467;
  const SWord64 s66 = ext_ident_word64_468;
  const SWord64 s67 = ext_ident_word64_469;
  const SWord64 s68 = ext_ident_word64_470;
  const SWord64 s69 = ext_ident_word64_471;
  const SWord64 s70 = ext_ident_word64_472;
  const SWord64 s71 = ext_ident_word64_473;
  const SDouble s72 = ext_ident_double_482;
  const SWord64 s73 = ext_ident_word64_475;
  const SWord64 s74 = ext_ident_word64_476;
  const SWord64 s75 = ext_ident_word64_477;
  const SWord64 s76 = ext_ident_word64_478;
  const SWord64 s77 = ext_ident_word64_479;
  const SWord64 s78 = ext_ident_word64_480;
  const SWord64 s79 = ext_ident_word64_481;
  const SDouble s80 = ext_ident_double_485;
  const SDouble s81 = ext_ident_double_484;
  const SDouble s82 = ext_ident_double_486;
  const SDouble s83 = ext_ownship_velocity_z;
  const SDouble s84 = ext_ident_double_510;
  const SDouble s85 = ext_ident_double_489;
  const SDouble s86 = ext_ident_double_506;
  const SDouble s87 = ext_ident_double_497;
  const SWord64 s88 = ext_ident_word64_490;
  const SWord64 s89 = ext_ident_word64_491;
  const SWord64 s90 = ext_ident_word64_492;
  const SWord64 s91 = ext_ident_word64_493;
  const SWord64 s92 = ext_ident_word64_494;
  const SWord64 s93 = ext_ident_word64_495;
  const SWord64 s94 = ext_ident_word64_496;
  const SDouble s95 = ext_ident_double_505;
  const SWord64 s96 = ext_ident_word64_498;
  const SWord64 s97 = ext_ident_word64_499;
  const SWord64 s98 = ext_ident_word64_500;
  const SWord64 s99 = ext_ident_word64_501;
  const SWord64 s100 = ext_ident_word64_502;
  const SWord64 s101 = ext_ident_word64_503;
  const SWord64 s102 = ext_ident_word64_504;
  const SDouble s103 = ext_ident_double_508;
  const SDouble s104 = ext_ident_double_507;
  const SDouble s105 = ext_ident_double_509;
  const SDouble s106 = ext_ident_double_533;
  const SDouble s107 = ext_ident_double_532;
  const SDouble s108 = ext_ident_double_511;
  const SDouble s109 = ext_ident_double_528;
  const SDouble s110 = ext_ident_double_519;
  const SWord64 s111 = ext_ident_word64_512;
  const SWord64 s112 = ext_ident_word64_513;
  const SWord64 s113 = ext_ident_word64_514;
  const SWord64 s114 = ext_ident_word64_515;
  const SWord64 s115 = ext_ident_word64_516;
  const SWord64 s116 = ext_ident_word64_517;
  const SWord64 s117 = ext_ident_word64_518;
  const SDouble s118 = ext_ident_double_527;
  const SWord64 s119 = ext_ident_word64_520;
  const SWord64 s120 = ext_ident_word64_521;
  const SWord64 s121 = ext_ident_word64_522;
  const SWord64 s122 = ext_ident_word64_523;
  const SWord64 s123 = ext_ident_word64_524;
  const SWord64 s124 = ext_ident_word64_525;
  const SWord64 s125 = ext_ident_word64_526;
  const SDouble s126 = ext_ident_double_530;
  const SDouble s127 = ext_ident_double_529;
  const SDouble s128 = ext_ident_double_531;
  const SDouble s129 = ext_ident_double_627;
  const SDouble s130 = ext_ident_double_626;
  const SDouble s131 = ext_ident_double_557;
  const SDouble s132 = ext_ident_double_536;
  const SDouble s133 = ext_ident_double_553;
  const SDouble s134 = ext_ident_double_544;
  const SWord64 s135 = ext_ident_word64_537;
  const SWord64 s136 = ext_ident_word64_538;
  const SWord64 s137 = ext_ident_word64_539;
  const SWord64 s138 = ext_ident_word64_540;
  const SWord64 s139 = ext_ident_word64_541;
  const SWord64 s140 = ext_ident_word64_542;
  const SWord64 s141 = ext_ident_word64_543;
  const SDouble s142 = ext_ident_double_552;
  const SWord64 s143 = ext_ident_word64_545;
  const SWord64 s144 = ext_ident_word64_546;
  const SWord64 s145 = ext_ident_word64_547;
  const SWord64 s146 = ext_ident_word64_548;
  const SWord64 s147 = ext_ident_word64_549;
  const SWord64 s148 = ext_ident_word64_550;
  const SWord64 s149 = ext_ident_word64_551;
  const SDouble s150 = ext_ident_double_555;
  const SDouble s151 = ext_ident_double_554;
  const SDouble s152 = ext_ident_double_556;
  const SDouble s153 = ext_ident_double_580;
  const SDouble s154 = ext_ident_double_579;
  const SDouble s155 = ext_ident_double_558;
  const SDouble s156 = ext_ident_double_575;
  const SDouble s157 = ext_ident_double_566;
  const SWord64 s158 = ext_ident_word64_559;
  const SWord64 s159 = ext_ident_word64_560;
  const SWord64 s160 = ext_ident_word64_561;
  const SWord64 s161 = ext_ident_word64_562;
  const SWord64 s162 = ext_ident_word64_563;
  const SWord64 s163 = ext_ident_word64_564;
  const SWord64 s164 = ext_ident_word64_565;
  const SDouble s165 = ext_ident_double_574;
  const SWord64 s166 = ext_ident_word64_567;
  const SWord64 s167 = ext_ident_word64_568;
  const SWord64 s168 = ext_ident_word64_569;
  const SWord64 s169 = ext_ident_word64_570;
  const SWord64 s170 = ext_ident_word64_571;
  const SWord64 s171 = ext_ident_word64_572;
  const SWord64 s172 = ext_ident_word64_573;
  const SDouble s173 = ext_ident_double_577;
  const SDouble s174 = ext_ident_double_576;
  const SDouble s175 = ext_ident_double_578;
  const SDouble s176 = ext_ident_double_602;
  const SDouble s177 = ext_ident_double_581;
  const SDouble s178 = ext_ident_double_598;
  const SDouble s179 = ext_ident_double_589;
  const SWord64 s180 = ext_ident_word64_582;
  const SWord64 s181 = ext_ident_word64_583;
  const SWord64 s182 = ext_ident_word64_584;
  const SWord64 s183 = ext_ident_word64_585;
  const SWord64 s184 = ext_ident_word64_586;
  const SWord64 s185 = ext_ident_word64_587;
  const SWord64 s186 = ext_ident_word64_588;
  const SDouble s187 = ext_ident_double_597;
  const SWord64 s188 = ext_ident_word64_590;
  const SWord64 s189 = ext_ident_word64_591;
  const SWord64 s190 = ext_ident_word64_592;
  const SWord64 s191 = ext_ident_word64_593;
  const SWord64 s192 = ext_ident_word64_594;
  const SWord64 s193 = ext_ident_word64_595;
  const SWord64 s194 = ext_ident_word64_596;
  const SDouble s195 = ext_ident_double_600;
  const SDouble s196 = ext_ident_double_599;
  const SDouble s197 = ext_ident_double_601;
  const SDouble s198 = ext_ident_double_625;
  const SDouble s199 = ext_ident_double_624;
  const SDouble s200 = ext_ident_double_603;
  const SDouble s201 = ext_ident_double_620;
  const SDouble s202 = ext_ident_double_611;
  const SWord64 s203 = ext_ident_word64_604;
  const SWord64 s204 = ext_ident_word64_605;
  const SWord64 s205 = ext_ident_word64_606;
  const SWord64 s206 = ext_ident_word64_607;
  const SWord64 s207 = ext_ident_word64_608;
  const SWord64 s208 = ext_ident_word64_609;
  const SWord64 s209 = ext_ident_word64_610;
  const SDouble s210 = ext_ident_double_619;
  const SWord64 s211 = ext_ident_word64_612;
  const SWord64 s212 = ext_ident_word64_613;
  const SWord64 s213 = ext_ident_word64_614;
  const SWord64 s214 = ext_ident_word64_615;
  const SWord64 s215 = ext_ident_word64_616;
  const SWord64 s216 = ext_ident_word64_617;
  const SWord64 s217 = ext_ident_word64_618;
  const SDouble s218 = ext_ident_double_622;
  const SDouble s219 = ext_ident_double_621;
  const SDouble s220 = ext_ident_double_623;
  const SDouble s221 = ext_ident_double_720;
  const SDouble s222 = ext_ident_double_719;
  const SDouble s223 = ext_ident_double_650;
  const SDouble s224 = ext_ident_double_629;
  const SDouble s225 = ext_ident_double_646;
  const SDouble s226 = ext_ident_double_637;
  const SWord64 s227 = ext_ident_word64_630;
  const SWord64 s228 = ext_ident_word64_631;
  const SWord64 s229 = ext_ident_word64_632;
  const SWord64 s230 = ext_ident_word64_633;
  const SWord64 s231 = ext_ident_word64_634;
  const SWord64 s232 = ext_ident_word64_635;
  const SWord64 s233 = ext_ident_word64_636;
  const SDouble s234 = ext_ident_double_645;
  const SWord64 s235 = ext_ident_word64_638;
  const SWord64 s236 = ext_ident_word64_639;
  const SWord64 s237 = ext_ident_word64_640;
  const SWord64 s238 = ext_ident_word64_641;
  const SWord64 s239 = ext_ident_word64_642;
  const SWord64 s240 = ext_ident_word64_643;
  const SWord64 s241 = ext_ident_word64_644;
  const SDouble s242 = ext_ident_double_648;
  const SDouble s243 = ext_ident_double_647;
  const SDouble s244 = ext_ident_double_649;
  const SDouble s245 = ext_ident_double_673;
  const SDouble s246 = ext_ident_double_672;
  const SDouble s247 = ext_ident_double_651;
  const SDouble s248 = ext_ident_double_668;
  const SDouble s249 = ext_ident_double_659;
  const SWord64 s250 = ext_ident_word64_652;
  const SWord64 s251 = ext_ident_word64_653;
  const SWord64 s252 = ext_ident_word64_654;
  const SWord64 s253 = ext_ident_word64_655;
  const SWord64 s254 = ext_ident_word64_656;
  const SWord64 s255 = ext_ident_word64_657;
  const SWord64 s256 = ext_ident_word64_658;
  const SDouble s257 = ext_ident_double_667;
  const SWord64 s258 = ext_ident_word64_660;
  const SWord64 s259 = ext_ident_word64_661;
  const SWord64 s260 = ext_ident_word64_662;
  const SWord64 s261 = ext_ident_word64_663;
  const SWord64 s262 = ext_ident_word64_664;
  const SWord64 s263 = ext_ident_word64_665;
  const SWord64 s264 = ext_ident_word64_666;
  const SDouble s265 = ext_ident_double_670;
  const SDouble s266 = ext_ident_double_669;
  const SDouble s267 = ext_ident_double_671;
  const SDouble s268 = ext_ident_double_695;
  const SDouble s269 = ext_ident_double_674;
  const SDouble s270 = ext_ident_double_691;
  const SDouble s271 = ext_ident_double_682;
  const SWord64 s272 = ext_ident_word64_675;
  const SWord64 s273 = ext_ident_word64_676;
  const SWord64 s274 = ext_ident_word64_677;
  const SWord64 s275 = ext_ident_word64_678;
  const SWord64 s276 = ext_ident_word64_679;
  const SWord64 s277 = ext_ident_word64_680;
  const SWord64 s278 = ext_ident_word64_681;
  const SDouble s279 = ext_ident_double_690;
  const SWord64 s280 = ext_ident_word64_683;
  const SWord64 s281 = ext_ident_word64_684;
  const SWord64 s282 = ext_ident_word64_685;
  const SWord64 s283 = ext_ident_word64_686;
  const SWord64 s284 = ext_ident_word64_687;
  const SWord64 s285 = ext_ident_word64_688;
  const SWord64 s286 = ext_ident_word64_689;
  const SDouble s287 = ext_ident_double_693;
  const SDouble s288 = ext_ident_double_692;
  const SDouble s289 = ext_ident_double_694;
  const SDouble s290 = ext_ident_double_718;
  const SDouble s291 = ext_ident_double_717;
  const SDouble s292 = ext_ident_double_696;
  const SDouble s293 = ext_ident_double_713;
  const SDouble s294 = ext_ident_double_704;
  const SWord64 s295 = ext_ident_word64_697;
  const SWord64 s296 = ext_ident_word64_698;
  const SWord64 s297 = ext_ident_word64_699;
  const SWord64 s298 = ext_ident_word64_700;
  const SWord64 s299 = ext_ident_word64_701;
  const SWord64 s300 = ext_ident_word64_702;
  const SWord64 s301 = ext_ident_word64_703;
  const SDouble s302 = ext_ident_double_712;
  const SWord64 s303 = ext_ident_word64_705;
  const SWord64 s304 = ext_ident_word64_706;
  const SWord64 s305 = ext_ident_word64_707;
  const SWord64 s306 = ext_ident_word64_708;
  const SWord64 s307 = ext_ident_word64_709;
  const SWord64 s308 = ext_ident_word64_710;
  const SWord64 s309 = ext_ident_word64_711;
  const SDouble s310 = ext_ident_double_715;
  const SDouble s311 = ext_ident_double_714;
  const SDouble s312 = ext_ident_double_716;
  const SDouble s313 = ext_ident_double_811;
  const SDouble s314 = ext_ident_double_742;
  const SDouble s315 = ext_ident_double_721;
  const SDouble s316 = ext_ident_double_738;
  const SDouble s317 = ext_ident_double_729;
  const SWord64 s318 = ext_ident_word64_722;
  const SWord64 s319 = ext_ident_word64_723;
  const SWord64 s320 = ext_ident_word64_724;
  const SWord64 s321 = ext_ident_word64_725;
  const SWord64 s322 = ext_ident_word64_726;
  const SWord64 s323 = ext_ident_word64_727;
  const SWord64 s324 = ext_ident_word64_728;
  const SDouble s325 = ext_ident_double_737;
  const SWord64 s326 = ext_ident_word64_730;
  const SWord64 s327 = ext_ident_word64_731;
  const SWord64 s328 = ext_ident_word64_732;
  const SWord64 s329 = ext_ident_word64_733;
  const SWord64 s330 = ext_ident_word64_734;
  const SWord64 s331 = ext_ident_word64_735;
  const SWord64 s332 = ext_ident_word64_736;
  const SDouble s333 = ext_ident_double_740;
  const SDouble s334 = ext_ident_double_739;
  const SDouble s335 = ext_ident_double_741;
  const SDouble s336 = ext_ident_double_765;
  const SDouble s337 = ext_ident_double_764;
  const SDouble s338 = ext_ident_double_743;
  const SDouble s339 = ext_ident_double_760;
  const SDouble s340 = ext_ident_double_751;
  const SWord64 s341 = ext_ident_word64_744;
  const SWord64 s342 = ext_ident_word64_745;
  const SWord64 s343 = ext_ident_word64_746;
  const SWord64 s344 = ext_ident_word64_747;
  const SWord64 s345 = ext_ident_word64_748;
  const SWord64 s346 = ext_ident_word64_749;
  const SWord64 s347 = ext_ident_word64_750;
  const SDouble s348 = ext_ident_double_759;
  const SWord64 s349 = ext_ident_word64_752;
  const SWord64 s350 = ext_ident_word64_753;
  const SWord64 s351 = ext_ident_word64_754;
  const SWord64 s352 = ext_ident_word64_755;
  const SWord64 s353 = ext_ident_word64_756;
  const SWord64 s354 = ext_ident_word64_757;
  const SWord64 s355 = ext_ident_word64_758;
  const SDouble s356 = ext_ident_double_762;
  const SDouble s357 = ext_ident_double_761;
  const SDouble s358 = ext_ident_double_763;
  const SDouble s359 = ext_ident_double_787;
  const SDouble s360 = ext_ident_double_766;
  const SDouble s361 = ext_ident_double_783;
  const SDouble s362 = ext_ident_double_774;
  const SWord64 s363 = ext_ident_word64_767;
  const SWord64 s364 = ext_ident_word64_768;
  const SWord64 s365 = ext_ident_word64_769;
  const SWord64 s366 = ext_ident_word64_770;
  const SWord64 s367 = ext_ident_word64_771;
  const SWord64 s368 = ext_ident_word64_772;
  const SWord64 s369 = ext_ident_word64_773;
  const SDouble s370 = ext_ident_double_782;
  const SWord64 s371 = ext_ident_word64_775;
  const SWord64 s372 = ext_ident_word64_776;
  const SWord64 s373 = ext_ident_word64_777;
  const SWord64 s374 = ext_ident_word64_778;
  const SWord64 s375 = ext_ident_word64_779;
  const SWord64 s376 = ext_ident_word64_780;
  const SWord64 s377 = ext_ident_word64_781;
  const SDouble s378 = ext_ident_double_785;
  const SDouble s379 = ext_ident_double_784;
  const SDouble s380 = ext_ident_double_786;
  const SDouble s381 = ext_ident_double_810;
  const SDouble s382 = ext_ident_double_809;
  const SDouble s383 = ext_ident_double_788;
  const SDouble s384 = ext_ident_double_805;
  const SDouble s385 = ext_ident_double_796;
  const SWord64 s386 = ext_ident_word64_789;
  const SWord64 s387 = ext_ident_word64_790;
  const SWord64 s388 = ext_ident_word64_791;
  const SWord64 s389 = ext_ident_word64_792;
  const SWord64 s390 = ext_ident_word64_793;
  const SWord64 s391 = ext_ident_word64_794;
  const SWord64 s392 = ext_ident_word64_795;
  const SDouble s393 = ext_ident_double_804;
  const SWord64 s394 = ext_ident_word64_797;
  const SWord64 s395 = ext_ident_word64_798;
  const SWord64 s396 = ext_ident_word64_799;
  const SWord64 s397 = ext_ident_word64_800;
  const SWord64 s398 = ext_ident_word64_801;
  const SWord64 s399 = ext_ident_word64_802;
  const SWord64 s400 = ext_ident_word64_803;
  const SDouble s401 = ext_ident_double_807;
  const SDouble s402 = ext_ident_double_806;
  const SDouble s403 = ext_ident_double_808;
  const SDouble s404 = s0 - s34;
  const SDouble s405 = s404 /* down_dist */;

  return s405;
}
