/* File: "ext_ident_double_1189_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: maxi",color=plum, style=filled]
0 -> 1
2 [label="op3: mux",color=green4, style=filled]
1 -> 2
3 [label="op2: >=",color=green4, style=filled]
2 -> 3
4 [label="const: 0.0",color=red1, style=filled]
3 -> 4
5 [label="op2: -",color=green4, style=filled]
3 -> 5
6 [label="ext_ident_double_1120",color=cyan4, style=filled]
5 -> 6
650 [label="ext_ident_double_1143",color=cyan4, style=filled]
5 -> 650
1309 [label="const: 0.0",color=red1, style=filled]
2 -> 1309
1310 [label="op2: -",color=green4, style=filled]
2 -> 1310
1311 [label="ext_ident_double_1165",color=cyan4, style=filled]
1310 -> 1311
1955 [label="ext_ident_double_1188",color=cyan4, style=filled]
1310 -> 1955


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((( (((0.0) >= (((ext_ident_double_1120) - (ext_ident_double_1143))))) ? (0.0) : (((ext_ident_double_1165) - (ext_ident_double_1188))))));
*/
SDouble ext_ident_double_1189_arg0(const SDouble ext_ident_double_1120,
                                   const SDouble ext_ident_double_1099,
                                   const SDouble ext_ownship_position_x,
                                   const SDouble ext_intruder_position_x,
                                   const SDouble ext_ownship_velocity_x,
                                   const SDouble ext_intruder_velocity_x,
                                   const SDouble ext_ownship_position_y,
                                   const SDouble ext_intruder_position_y,
                                   const SDouble ext_ownship_velocity_y,
                                   const SDouble ext_intruder_velocity_y,
                                   const SDouble ext_ident_double_1116,
                                   const SDouble ext_ident_double_1107,
                                   const SWord64 ext_ident_word64_1100,
                                   const SDouble ext_ownship_position_z,
                                   const SWord64 ext_ident_word64_1101,
                                   const SWord64 ext_ident_word64_1102,
                                   const SWord64 ext_ident_word64_1103,
                                   const SWord64 ext_ident_word64_1104,
                                   const SWord64 ext_ident_word64_1105,
                                   const SWord64 ext_ident_word64_1106,
                                   const SDouble ext_ident_double_1115,
                                   const SWord64 ext_ident_word64_1108,
                                   const SWord64 ext_ident_word64_1109,
                                   const SWord64 ext_ident_word64_1110,
                                   const SWord64 ext_ident_word64_1111,
                                   const SWord64 ext_ident_word64_1112,
                                   const SWord64 ext_ident_word64_1113,
                                   const SWord64 ext_ident_word64_1114,
                                   const SDouble ext_ident_double_1118,
                                   const SDouble ext_ident_double_1117,
                                   const SDouble ext_ident_double_1119,
                                   const SDouble ext_ident_double_1143,
                                   const SDouble ext_ident_double_1142,
                                   const SDouble ext_ident_double_1121,
                                   const SDouble ext_ident_double_1138,
                                   const SDouble ext_ident_double_1129,
                                   const SWord64 ext_ident_word64_1122,
                                   const SWord64 ext_ident_word64_1123,
                                   const SWord64 ext_ident_word64_1124,
                                   const SWord64 ext_ident_word64_1125,
                                   const SWord64 ext_ident_word64_1126,
                                   const SWord64 ext_ident_word64_1127,
                                   const SWord64 ext_ident_word64_1128,
                                   const SDouble ext_ident_double_1137,
                                   const SWord64 ext_ident_word64_1130,
                                   const SWord64 ext_ident_word64_1131,
                                   const SWord64 ext_ident_word64_1132,
                                   const SWord64 ext_ident_word64_1133,
                                   const SWord64 ext_ident_word64_1134,
                                   const SWord64 ext_ident_word64_1135,
                                   const SWord64 ext_ident_word64_1136,
                                   const SDouble ext_ident_double_1140,
                                   const SDouble ext_ident_double_1139,
                                   const SDouble ext_ident_double_1141,
                                   const SDouble ext_ownship_velocity_z,
                                   const SDouble ext_ident_double_1165,
                                   const SDouble ext_ident_double_1144,
                                   const SDouble ext_ident_double_1161,
                                   const SDouble ext_ident_double_1152,
                                   const SWord64 ext_ident_word64_1145,
                                   const SWord64 ext_ident_word64_1146,
                                   const SWord64 ext_ident_word64_1147,
                                   const SWord64 ext_ident_word64_1148,
                                   const SWord64 ext_ident_word64_1149,
                                   const SWord64 ext_ident_word64_1150,
                                   const SWord64 ext_ident_word64_1151,
                                   const SDouble ext_ident_double_1160,
                                   const SWord64 ext_ident_word64_1153,
                                   const SWord64 ext_ident_word64_1154,
                                   const SWord64 ext_ident_word64_1155,
                                   const SWord64 ext_ident_word64_1156,
                                   const SWord64 ext_ident_word64_1157,
                                   const SWord64 ext_ident_word64_1158,
                                   const SWord64 ext_ident_word64_1159,
                                   const SDouble ext_ident_double_1163,
                                   const SDouble ext_ident_double_1162,
                                   const SDouble ext_ident_double_1164,
                                   const SDouble ext_ident_double_1188,
                                   const SDouble ext_ident_double_1187,
                                   const SDouble ext_ident_double_1166,
                                   const SDouble ext_ident_double_1183,
                                   const SDouble ext_ident_double_1174,
                                   const SWord64 ext_ident_word64_1167,
                                   const SWord64 ext_ident_word64_1168,
                                   const SWord64 ext_ident_word64_1169,
                                   const SWord64 ext_ident_word64_1170,
                                   const SWord64 ext_ident_word64_1171,
                                   const SWord64 ext_ident_word64_1172,
                                   const SWord64 ext_ident_word64_1173,
                                   const SDouble ext_ident_double_1182,
                                   const SWord64 ext_ident_word64_1175,
                                   const SWord64 ext_ident_word64_1176,
                                   const SWord64 ext_ident_word64_1177,
                                   const SWord64 ext_ident_word64_1178,
                                   const SWord64 ext_ident_word64_1179,
                                   const SWord64 ext_ident_word64_1180,
                                   const SWord64 ext_ident_word64_1181,
                                   const SDouble ext_ident_double_1185,
                                   const SDouble ext_ident_double_1184,
                                   const SDouble ext_ident_double_1186)
{
  const SDouble s0 = ext_ident_double_1120;
  const SDouble s1 = ext_ident_double_1099;
  const SDouble s2 = ext_ownship_position_x;
  const SDouble s3 = ext_intruder_position_x;
  const SDouble s4 = ext_ownship_velocity_x;
  const SDouble s5 = ext_intruder_velocity_x;
  const SDouble s6 = ext_ownship_position_y;
  const SDouble s7 = ext_intruder_position_y;
  const SDouble s8 = ext_ownship_velocity_y;
  const SDouble s9 = ext_intruder_velocity_y;
  const SDouble s10 = ext_ident_double_1116;
  const SDouble s11 = ext_ident_double_1107;
  const SWord64 s12 = ext_ident_word64_1100;
  const SDouble s13 = ext_ownship_position_z;
  const SWord64 s14 = ext_ident_word64_1101;
  const SWord64 s15 = ext_ident_word64_1102;
  const SWord64 s16 = ext_ident_word64_1103;
  const SWord64 s17 = ext_ident_word64_1104;
  const SWord64 s18 = ext_ident_word64_1105;
  const SWord64 s19 = ext_ident_word64_1106;
  const SDouble s20 = ext_ident_double_1115;
  const SWord64 s21 = ext_ident_word64_1108;
  const SWord64 s22 = ext_ident_word64_1109;
  const SWord64 s23 = ext_ident_word64_1110;
  const SWord64 s24 = ext_ident_word64_1111;
  const SWord64 s25 = ext_ident_word64_1112;
  const SWord64 s26 = ext_ident_word64_1113;
  const SWord64 s27 = ext_ident_word64_1114;
  const SDouble s28 = ext_ident_double_1118;
  const SDouble s29 = ext_ident_double_1117;
  const SDouble s30 = ext_ident_double_1119;
  const SDouble s31 = ext_ident_double_1143;
  const SDouble s32 = ext_ident_double_1142;
  const SDouble s33 = ext_ident_double_1121;
  const SDouble s34 = ext_ident_double_1138;
  const SDouble s35 = ext_ident_double_1129;
  const SWord64 s36 = ext_ident_word64_1122;
  const SWord64 s37 = ext_ident_word64_1123;
  const SWord64 s38 = ext_ident_word64_1124;
  const SWord64 s39 = ext_ident_word64_1125;
  const SWord64 s40 = ext_ident_word64_1126;
  const SWord64 s41 = ext_ident_word64_1127;
  const SWord64 s42 = ext_ident_word64_1128;
  const SDouble s43 = ext_ident_double_1137;
  const SWord64 s44 = ext_ident_word64_1130;
  const SWord64 s45 = ext_ident_word64_1131;
  const SWord64 s46 = ext_ident_word64_1132;
  const SWord64 s47 = ext_ident_word64_1133;
  const SWord64 s48 = ext_ident_word64_1134;
  const SWord64 s49 = ext_ident_word64_1135;
  const SWord64 s50 = ext_ident_word64_1136;
  const SDouble s51 = ext_ident_double_1140;
  const SDouble s52 = ext_ident_double_1139;
  const SDouble s53 = ext_ident_double_1141;
  const SDouble s54 = ext_ownship_velocity_z;
  const SDouble s55 = ext_ident_double_1165;
  const SDouble s56 = ext_ident_double_1144;
  const SDouble s57 = ext_ident_double_1161;
  const SDouble s58 = ext_ident_double_1152;
  const SWord64 s59 = ext_ident_word64_1145;
  const SWord64 s60 = ext_ident_word64_1146;
  const SWord64 s61 = ext_ident_word64_1147;
  const SWord64 s62 = ext_ident_word64_1148;
  const SWord64 s63 = ext_ident_word64_1149;
  const SWord64 s64 = ext_ident_word64_1150;
  const SWord64 s65 = ext_ident_word64_1151;
  const SDouble s66 = ext_ident_double_1160;
  const SWord64 s67 = ext_ident_word64_1153;
  const SWord64 s68 = ext_ident_word64_1154;
  const SWord64 s69 = ext_ident_word64_1155;
  const SWord64 s70 = ext_ident_word64_1156;
  const SWord64 s71 = ext_ident_word64_1157;
  const SWord64 s72 = ext_ident_word64_1158;
  const SWord64 s73 = ext_ident_word64_1159;
  const SDouble s74 = ext_ident_double_1163;
  const SDouble s75 = ext_ident_double_1162;
  const SDouble s76 = ext_ident_double_1164;
  const SDouble s77 = ext_ident_double_1188;
  const SDouble s78 = ext_ident_double_1187;
  const SDouble s79 = ext_ident_double_1166;
  const SDouble s80 = ext_ident_double_1183;
  const SDouble s81 = ext_ident_double_1174;
  const SWord64 s82 = ext_ident_word64_1167;
  const SWord64 s83 = ext_ident_word64_1168;
  const SWord64 s84 = ext_ident_word64_1169;
  const SWord64 s85 = ext_ident_word64_1170;
  const SWord64 s86 = ext_ident_word64_1171;
  const SWord64 s87 = ext_ident_word64_1172;
  const SWord64 s88 = ext_ident_word64_1173;
  const SDouble s89 = ext_ident_double_1182;
  const SWord64 s90 = ext_ident_word64_1175;
  const SWord64 s91 = ext_ident_word64_1176;
  const SWord64 s92 = ext_ident_word64_1177;
  const SWord64 s93 = ext_ident_word64_1178;
  const SWord64 s94 = ext_ident_word64_1179;
  const SWord64 s95 = ext_ident_word64_1180;
  const SWord64 s96 = ext_ident_word64_1181;
  const SDouble s97 = ext_ident_double_1185;
  const SDouble s98 = ext_ident_double_1184;
  const SDouble s99 = ext_ident_double_1186;
  const SDouble s101 = s0 - s31;
  const SBool   s102 = 0.0 >= s101;
  const SDouble s103 = s55 - s77;
  const SDouble s104 = s102 ? 0.0 : s103;
  const SDouble s105 = s104 /* maxi */;

  return s105;
}
