/* File: "ext_ident_double_20_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: sq",color=plum, style=filled]
0 -> 1
2 [label="op2: *",color=green4, style=filled]
1 -> 2
3 [label="ext_ident_double_11",color=cyan4, style=filled]
2 -> 3
293 [label="ext_ident_double_19",color=cyan4, style=filled]
2 -> 293


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((ext_ident_double_11) * (ext_ident_double_19))));
*/
SDouble ext_ident_double_20_arg0(const SDouble ext_ident_double_11,
                                 const SWord64 ext_ident_word64_4,
                                 const SDouble ext_ownship_position_z,
                                 const SWord64 ext_ident_word64_5, const SWord64 ext_ident_word64_6,
                                 const SWord64 ext_ident_word64_7, const SWord64 ext_ident_word64_8,
                                 const SWord64 ext_ident_word64_9,
                                 const SWord64 ext_ident_word64_10,
                                 const SDouble ext_ident_double_19,
                                 const SWord64 ext_ident_word64_12,
                                 const SWord64 ext_ident_word64_13,
                                 const SWord64 ext_ident_word64_14,
                                 const SWord64 ext_ident_word64_15,
                                 const SWord64 ext_ident_word64_16,
                                 const SWord64 ext_ident_word64_17,
                                 const SWord64 ext_ident_word64_18)
{
  const SDouble s0 = ext_ident_double_11;
  const SDouble s9 = ext_ident_double_19;
  const SDouble s17 = s0 * s9;
  const SDouble s18 = s17 /* sq */;

  return s18;
}
