/* File: "ext_ident_double_39_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "normsq2dim" ext_ident_double_38
*/
/*@
 assigns \nothing;
 ensures \result == ((ext_ident_double_38));
*/
SDouble ext_ident_double_39_arg0(const SDouble ext_ident_double_38,
                                 const SDouble ext_ownship_position_x,
                                 const SDouble ext_intruder_position_x,
                                 const SDouble ext_ownship_position_y,
                                 const SDouble ext_intruder_position_y)
{
  const SDouble s0 = ext_ident_double_38;
  const SDouble s5 = s0 /* normsq2dim */;

  return s5;
}
