/* File: "ext_ident_double_40_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: normsq2dim",color=plum, style=filled]
0 -> 1
2 [label="ext_ident_double_39",color=cyan4, style=filled]
1 -> 2


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((ext_ident_double_39));
*/
SDouble ext_ident_double_40_arg0(const SDouble ext_ident_double_39,
                                 const SDouble ext_ownship_velocity_x,
                                 const SDouble ext_intruder_velocity_x,
                                 const SDouble ext_ownship_velocity_y,
                                 const SDouble ext_intruder_velocity_y)
{
  const SDouble s0 = ext_ident_double_39;
  const SDouble s5 = s0 /* normsq2dim */;

  return s5;
}
