/* File: "ext_ident_double_1715_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: norm2dim",color=plum, style=filled]
0 -> 1
2 [label="ext_sqrt_1714",color=cyan4, style=filled]
1 -> 2


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((ext_sqrt_1714));
*/
SDouble ext_ident_double_1715_arg0(const SDouble ext_sqrt_1714,
                                   const SDouble ext_ident_double_1713,
                                   const SDouble ext_ident_double_1712,
                                   const SDouble ext_ownship_position_x,
                                   const SDouble ext_intruder_position_x,
                                   const SDouble ext_ownship_position_y,
                                   const SDouble ext_intruder_position_y)
{
  const SDouble s0 = ext_sqrt_1714;
  const SDouble s1 = ext_ident_double_1713;
  const SDouble s2 = ext_ident_double_1712;
  const SDouble s3 = ext_ownship_position_x;
  const SDouble s4 = ext_intruder_position_x;
  const SDouble s5 = ext_ownship_position_y;
  const SDouble s6 = ext_intruder_position_y;
  const SDouble s7 = s0 /* norm2dim */;

  return s7;
}
