/* File: "update_state_1.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*ACSL to write
 (s1 + 1)
*/
/*@
 assigns \nothing;
 ensures \result == (((queue_1[ptr_1]) + (1)));
*/
SWord32 update_state_1(const SWord32 *queue_1, const SWord32 ptr_1)
{
  const SWord32 s0 = queue_1[0];
  const SWord32 s1 = ptr_1;
  const SWord32 s3 = s0 + 0x00000001UL;

  return s3;
}
