/* File: "ext_ident_bool_39_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "zCriterion_part2.1" ((Ext_ownship_velocity_z - Ext_intruder_velocity_z) < 0.0)
*/
/*@
 assigns \nothing;
 ensures \result == ((((((ext_ownship_velocity_z) - (ext_intruder_velocity_z))) < (0.0))));
*/
SBool ext_ident_bool_39_arg0(const SDouble ext_ownship_velocity_z,
                             const SDouble ext_intruder_velocity_z)
{
  const SDouble s0 = ext_ownship_velocity_z;
  const SDouble s1 = ext_intruder_velocity_z;
  const SDouble s2 = s0 - s1;
  const SBool   s4 = s2 < 0.0;
  const SBool   s5 = s4 /* zCriterion_part2.1 */;

  return s5;
}
