/* File: "ext_ident_double_100_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: thetaVert_part1",color=plum, style=filled]
0 -> 1
2 [label="op2: -",color=green4, style=filled]
1 -> 2
3 [label="const: 0.0",color=red1, style=filled]
2 -> 3
4 [label="ext_ident_double_99",color=cyan4, style=filled]
2 -> 4


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((0.0) - (ext_ident_double_99))));
*/
SDouble ext_ident_double_100_arg0(const SDouble ext_ident_double_99,
                                  const SDouble ext_ownship_position_x,
                                  const SDouble ext_intruder_position_x,
                                  const SDouble ext_ownship_velocity_x,
                                  const SDouble ext_intruder_velocity_x,
                                  const SDouble ext_ownship_position_y,
                                  const SDouble ext_intruder_position_y,
                                  const SDouble ext_ownship_velocity_y,
                                  const SDouble ext_intruder_velocity_y)
{
  const SDouble s0 = ext_ident_double_99;
  const SDouble s10 = 0.0 - s0;
  const SDouble s11 = s10 /* thetaVert_part1 */;

  return s11;
}
