/* File: "ext_ident_bool_417_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: intersectsHalfPlane_part3",color=plum, style=filled]
0 -> 1
2 [label="op2: >=",color=green4, style=filled]
1 -> 2
3 [label="op2: *",color=green4, style=filled]
2 -> 3
4 [label="ext_direction_parameter_vertical",color=cyan1, style=filled]
3 -> 4
5 [label="op2: +",color=green4, style=filled]
3 -> 5
6 [label="op2: -",color=green4, style=filled]
5 -> 6
7 [label="ext_ownship_position_z",color=cyan1, style=filled]
6 -> 7
8 [label="ext_intruder_position_z",color=cyan1, style=filled]
6 -> 8
9 [label="op2: *",color=green4, style=filled]
5 -> 9
10 [label="ext_ident_double_416",color=cyan4, style=filled]
9 -> 10
751 [label="op2: -",color=green4, style=filled]
9 -> 751
752 [label="ext_ownship_planned_velocity_z",color=cyan1, style=filled]
751 -> 752
753 [label="ext_intruder_velocity_z",color=cyan1, style=filled]
751 -> 753
754 [label="op2: *",color=green4, style=filled]
2 -> 754
755 [label="ext_direction_parameter_vertical",color=cyan1, style=filled]
754 -> 755
756 [label="op2: *",color=green4, style=filled]
754 -> 756
757 [label="ext_direction_parameter_vertical",color=cyan1, style=filled]
756 -> 757
758 [label="ext_minimal_vertical_separation",color=cyan1, style=filled]
756 -> 758


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((((ext_direction_parameter_vertical) * (((((ext_ownship_position_z) - (ext_intruder_position_z))) + (((ext_ident_double_416) * (((ext_ownship_planned_velocity_z) - (ext_intruder_velocity_z))))))))) >= (((ext_direction_parameter_vertical) * (((ext_direction_parameter_vertical) * (ext_minimal_vertical_separation))))))));
*/
SBool ext_ident_bool_417_arg0(const SDouble ext_direction_parameter_vertical,
                              const SDouble ext_ownship_position_z,
                              const SDouble ext_intruder_position_z,
                              const SDouble ext_ident_double_416,
                              const SDouble ext_minimal_horizontal_separation,
                              const SDouble ext_ownship_position_x,
                              const SDouble ext_intruder_position_x,
                              const SDouble ext_ident_double_337,
                              const SDouble ext_ident_double_336,
                              const SDouble ext_ident_double_335,
                              const SDouble ext_ident_double_332,
                              const SDouble ext_ident_double_313,
                              const SDouble ext_ident_double_312,
                              const SDouble ext_ownship_velocity_x,
                              const SDouble ext_intruder_velocity_x,
                              const SDouble ext_ownship_position_y,
                              const SDouble ext_intruder_position_y,
                              const SDouble ext_ownship_velocity_y,
                              const SDouble ext_intruder_velocity_y,
                              const SDouble ext_ident_double_331,
                              const SDouble ext_ident_double_321, const SBool ext_ident_bool_318,
                              const SDouble ext_ident_double_317,
                              const SDouble ext_ident_double_314,
                              const SDouble ext_ident_double_316,
                              const SDouble ext_ident_double_315,
                              const SDouble ext_minimal_vertical_separation,
                              const SDouble ext_ident_double_320,
                              const SDouble ext_ident_double_319,
                              const SDouble ext_ident_double_330, const SDouble ext_sqrt_329,
                              const SDouble ext_ident_double_322,
                              const SDouble ext_ident_double_323,
                              const SDouble ext_ident_double_328,
                              const SDouble ext_ident_double_325,
                              const SDouble ext_ident_double_324,
                              const SDouble ext_ident_double_327,
                              const SDouble ext_ident_double_326,
                              const SDouble ext_ident_double_334,
                              const SDouble ext_ident_double_333,
                              const SDouble ext_ident_double_363,
                              const SDouble ext_ident_double_362,
                              const SDouble ext_ident_double_361,
                              const SDouble ext_ident_double_358,
                              const SDouble ext_ident_double_339,
                              const SDouble ext_ident_double_338,
                              const SDouble ext_ident_double_357,
                              const SDouble ext_ident_double_347, const SBool ext_ident_bool_344,
                              const SDouble ext_ident_double_343,
                              const SDouble ext_ident_double_340,
                              const SDouble ext_ident_double_342,
                              const SDouble ext_ident_double_341,
                              const SDouble ext_ident_double_346,
                              const SDouble ext_ident_double_345,
                              const SDouble ext_ident_double_356, const SDouble ext_sqrt_355,
                              const SDouble ext_ident_double_348,
                              const SDouble ext_ident_double_349,
                              const SDouble ext_ident_double_354,
                              const SDouble ext_ident_double_351,
                              const SDouble ext_ident_double_350,
                              const SDouble ext_ident_double_353,
                              const SDouble ext_ident_double_352,
                              const SDouble ext_ident_double_360,
                              const SDouble ext_ident_double_359,
                              const SDouble ext_ownship_planned_velocity_x,
                              const SDouble ext_ident_double_389,
                              const SDouble ext_ident_double_388,
                              const SDouble ext_ident_double_387,
                              const SDouble ext_ident_double_384,
                              const SDouble ext_ident_double_365,
                              const SDouble ext_ident_double_364,
                              const SDouble ext_ident_double_383,
                              const SDouble ext_ident_double_373, const SBool ext_ident_bool_370,
                              const SDouble ext_ident_double_369,
                              const SDouble ext_ident_double_366,
                              const SDouble ext_ident_double_368,
                              const SDouble ext_ident_double_367,
                              const SDouble ext_ident_double_372,
                              const SDouble ext_ident_double_371,
                              const SDouble ext_ident_double_382, const SDouble ext_sqrt_381,
                              const SDouble ext_ident_double_374,
                              const SDouble ext_ident_double_375,
                              const SDouble ext_ident_double_380,
                              const SDouble ext_ident_double_377,
                              const SDouble ext_ident_double_376,
                              const SDouble ext_ident_double_379,
                              const SDouble ext_ident_double_378,
                              const SDouble ext_ident_double_386,
                              const SDouble ext_ident_double_385,
                              const SDouble ext_ownship_planned_velocity_y,
                              const SDouble ext_ident_double_415,
                              const SDouble ext_ident_double_414,
                              const SDouble ext_ident_double_413,
                              const SDouble ext_ident_double_410,
                              const SDouble ext_ident_double_391,
                              const SDouble ext_ident_double_390,
                              const SDouble ext_ident_double_409,
                              const SDouble ext_ident_double_399, const SBool ext_ident_bool_396,
                              const SDouble ext_ident_double_395,
                              const SDouble ext_ident_double_392,
                              const SDouble ext_ident_double_394,
                              const SDouble ext_ident_double_393,
                              const SDouble ext_ident_double_398,
                              const SDouble ext_ident_double_397,
                              const SDouble ext_ident_double_408, const SDouble ext_sqrt_407,
                              const SDouble ext_ident_double_400,
                              const SDouble ext_ident_double_401,
                              const SDouble ext_ident_double_406,
                              const SDouble ext_ident_double_403,
                              const SDouble ext_ident_double_402,
                              const SDouble ext_ident_double_405,
                              const SDouble ext_ident_double_404,
                              const SDouble ext_ident_double_412,
                              const SDouble ext_ident_double_411,
                              const SDouble ext_ownship_planned_velocity_z,
                              const SDouble ext_intruder_velocity_z)
{
  const SDouble s0 = ext_direction_parameter_vertical;
  const SDouble s1 = ext_ownship_position_z;
  const SDouble s2 = ext_intruder_position_z;
  const SDouble s3 = ext_ident_double_416;
  const SDouble s26 = ext_minimal_vertical_separation;
  const SDouble s120 = ext_ownship_planned_velocity_z;
  const SDouble s121 = ext_intruder_velocity_z;
  const SDouble s122 = s1 - s2;
  const SDouble s123 = s120 - s121;
  const SDouble s124 = s3 * s123;
  const SDouble s125 = s122 + s124;
  const SDouble s126 = s0 * s125;
  const SDouble s127 = s0 * s26;
  const SDouble s128 = s0 * s127;
  const SBool   s129 = s126 >= s128;
  const SBool   s130 = s129 /* intersectsHalfPlane_part3 */;

  return s130;
}
