/* File: "ext_ident_bool_51_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "verticalCriterionLoss_part3" (Ext_maximum_time_for_violation >= Extf_ident_double(label "verticalCriterionLoss_part3.1" Extf_ident_double(label "ttez" (Extf_ident_double(label "ttez_dividend" ((Ext_minimal_vertical_separation * Extf_ident_double(label "ttez_part01" signum (Ext_ownship_velocity_z - Ext_intruder_velocity_z))) - Extf_ident_double(label "ttez_part02" (Ext_ownship_position_z - Ext_intruder_position_z)))) / Extf_ident_double(label "ttez_divisor" (Ext_ownship_velocity_z - Ext_intruder_velocity_z))))))
*/
/*@
 assigns \nothing;
 ensures \result == ((((ext_maximum_time_for_violation) >= (ext_ident_double_50))));
*/
SBool ext_ident_bool_51_arg0(const SDouble ext_maximum_time_for_violation,
                             const SDouble ext_ident_double_50,
                             const SDouble ext_ident_double_49,
                             const SDouble ext_ident_double_47,
                             const SDouble ext_minimal_vertical_separation,
                             const SDouble ext_ident_double_45,
                             const SDouble ext_ownship_velocity_z,
                             const SDouble ext_intruder_velocity_z,
                             const SDouble ext_ident_double_46,
                             const SDouble ext_ownship_position_z,
                             const SDouble ext_intruder_position_z,
                             const SDouble ext_ident_double_48)
{
  const SDouble s0 = ext_maximum_time_for_violation;
  const SDouble s1 = ext_ident_double_50;
  const SDouble s2 = ext_ident_double_49;
  const SDouble s3 = ext_ident_double_47;
  const SDouble s4 = ext_minimal_vertical_separation;
  const SDouble s5 = ext_ident_double_45;
  const SDouble s6 = ext_ownship_velocity_z;
  const SDouble s7 = ext_intruder_velocity_z;
  const SDouble s8 = ext_ident_double_46;
  const SDouble s9 = ext_ownship_position_z;
  const SDouble s10 = ext_intruder_position_z;
  const SDouble s11 = ext_ident_double_48;
  const SBool   s12 = s0 >= s1;
  const SBool   s13 = s12 /* verticalCriterionLoss_part3 */;

  return s13;
}
