/* File: "ext_ident_double_81_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: dirVert_part2",color=plum, style=filled]
0 -> 1
2 [label="op2: *",color=green4, style=filled]
1 -> 2
3 [label="ext_direction_parameter_vertical",color=cyan1, style=filled]
2 -> 3
4 [label="ext_ident_double_80",color=cyan4, style=filled]
2 -> 4


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((ext_direction_parameter_vertical) * (ext_ident_double_80))));
*/
SDouble ext_ident_double_81_arg0(const SDouble ext_direction_parameter_vertical,
                                 const SDouble ext_ident_double_80,
                                 const SDouble ext_ownship_position_z,
                                 const SDouble ext_intruder_position_z)
{
  const SDouble s0 = ext_direction_parameter_vertical;
  const SDouble s1 = ext_ident_double_80;
  const SDouble s4 = s0 * s1;
  const SDouble s5 = s4 /* dirVert_part2 */;

  return s5;
}
