/* File: "ext_ident_bool_105_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: dirVert_part1",color=plum, style=filled]
0 -> 1
2 [label="op2: >=",color=green4, style=filled]
1 -> 2
3 [label="ext_ident_double_104",color=cyan4, style=filled]
2 -> 3
19 [label="ext_minimal_vertical_separation",color=cyan1, style=filled]
2 -> 19


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((ext_ident_double_104) >= (ext_minimal_vertical_separation))));
*/
SBool ext_ident_bool_105_arg0(const SDouble ext_ident_double_104,
                              const SDouble ext_ident_double_101,
                              const SDouble ext_ownship_position_z,
                              const SDouble ext_intruder_position_z,
                              const SDouble ext_ident_double_103,
                              const SDouble ext_ident_double_102,
                              const SDouble ext_minimal_vertical_separation)
{
  const SDouble s0 = ext_ident_double_104;
  const SDouble s6 = ext_minimal_vertical_separation;
  const SBool   s7 = s0 >= s6;
  const SBool   s8 = s7 /* dirVert_part1 */;

  return s8;
}
