/* File: "ext_ident_bool_15_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "z_prop?(sz;v'z)" (((Ext_ownship_position_z - Ext_intruder_position_z) * (Ext_ownship_planned_velocity_z - Ext_intruder_velocity_z)) >= 0.0)
*/
/*@
 assigns \nothing;
 ensures \result == ((((((((ext_ownship_position_z) - (ext_intruder_position_z))) * (((ext_ownship_planned_velocity_z) - (ext_intruder_velocity_z))))) >= (0.0))));
*/
SBool ext_ident_bool_15_arg0(const SDouble ext_ownship_position_z,
                             const SDouble ext_intruder_position_z,
                             const SDouble ext_ownship_planned_velocity_z,
                             const SDouble ext_intruder_velocity_z)
{
  const SDouble s0 = ext_ownship_position_z;
  const SDouble s1 = ext_intruder_position_z;
  const SDouble s2 = ext_ownship_planned_velocity_z;
  const SDouble s3 = ext_intruder_velocity_z;
  const SDouble s4 = s0 - s1;
  const SDouble s5 = s2 - s3;
  const SDouble s6 = s4 * s5;
  const SBool   s8 = s6 >= 0.0;
  const SBool   s9 = s8 /* z_prop?(sz;v'z) */;

  return s9;
}
