/* File: "ext_ident_bool_61_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: criterion3D_part2",color=plum, style=filled]
0 -> 1
2 [label="op2: >=",color=green4, style=filled]
1 -> 2
3 [label="op2: +",color=green4, style=filled]
2 -> 3
4 [label="op2: *",color=green4, style=filled]
3 -> 4
5 [label="op2: -",color=green4, style=filled]
4 -> 5
6 [label="ext_ownship_position_x",color=cyan1, style=filled]
5 -> 6
7 [label="ext_intruder_position_x",color=cyan1, style=filled]
5 -> 7
8 [label="op2: -",color=green4, style=filled]
4 -> 8
9 [label="ext_ownship_planned_velocity_x",color=cyan1, style=filled]
8 -> 9
10 [label="ext_intruder_velocity_x",color=cyan1, style=filled]
8 -> 10
11 [label="op2: *",color=green4, style=filled]
3 -> 11
12 [label="op2: -",color=green4, style=filled]
11 -> 12
13 [label="ext_ownship_position_y",color=cyan1, style=filled]
12 -> 13
14 [label="ext_intruder_position_y",color=cyan1, style=filled]
12 -> 14
15 [label="op2: -",color=green4, style=filled]
11 -> 15
16 [label="ext_ownship_planned_velocity_y",color=cyan1, style=filled]
15 -> 16
17 [label="ext_intruder_velocity_y",color=cyan1, style=filled]
15 -> 17
18 [label="op2: *",color=green4, style=filled]
2 -> 18
19 [label="op2: *",color=green4, style=filled]
18 -> 19
20 [label="ext_direction_parameter_horizontal",color=cyan1, style=filled]
19 -> 20
21 [label="op2: /",color=green4, style=filled]
19 -> 21
22 [label="ext_ident_double_59",color=cyan4, style=filled]
21 -> 22
46 [label="ext_ident_double_60",color=cyan4, style=filled]
21 -> 46
49 [label="op2: -",color=green4, style=filled]
18 -> 49
50 [label="op2: *",color=green4, style=filled]
49 -> 50
51 [label="op2: -",color=green4, style=filled]
50 -> 51
52 [label="ext_ownship_position_x",color=cyan1, style=filled]
51 -> 52
53 [label="ext_intruder_position_x",color=cyan1, style=filled]
51 -> 53
54 [label="op2: -",color=green4, style=filled]
50 -> 54
55 [label="ext_ownship_planned_velocity_y",color=cyan1, style=filled]
54 -> 55
56 [label="ext_intruder_velocity_y",color=cyan1, style=filled]
54 -> 56
57 [label="op2: *",color=green4, style=filled]
49 -> 57
58 [label="op2: -",color=green4, style=filled]
57 -> 58
59 [label="ext_ownship_planned_velocity_x",color=cyan1, style=filled]
58 -> 59
60 [label="ext_intruder_velocity_x",color=cyan1, style=filled]
58 -> 60
61 [label="op2: -",color=green4, style=filled]
57 -> 61
62 [label="ext_ownship_position_y",color=cyan1, style=filled]
61 -> 62
63 [label="ext_intruder_position_y",color=cyan1, style=filled]
61 -> 63


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((((((((ext_ownship_position_x) - (ext_intruder_position_x))) * (((ext_ownship_planned_velocity_x) - (ext_intruder_velocity_x))))) + (((((ext_ownship_position_y) - (ext_intruder_position_y))) * (((ext_ownship_planned_velocity_y) - (ext_intruder_velocity_y))))))) >= (((((ext_direction_parameter_horizontal) * (((ext_ident_double_59) / (ext_ident_double_60))))) * (((((((ext_ownship_position_x) - (ext_intruder_position_x))) * (((ext_ownship_planned_velocity_y) - (ext_intruder_velocity_y))))) - (((((ext_ownship_planned_velocity_x) - (ext_intruder_velocity_x))) * (((ext_ownship_position_y) - (ext_intruder_position_y))))))))))));
*/
SBool ext_ident_bool_61_arg0(const SDouble ext_ownship_position_x,
                             const SDouble ext_intruder_position_x,
                             const SDouble ext_ownship_planned_velocity_x,
                             const SDouble ext_intruder_velocity_x,
                             const SDouble ext_ownship_position_y,
                             const SDouble ext_intruder_position_y,
                             const SDouble ext_ownship_planned_velocity_y,
                             const SDouble ext_intruder_velocity_y,
                             const SDouble ext_direction_parameter_horizontal,
                             const SDouble ext_ident_double_59, const SDouble ext_sqrt_58,
                             const SDouble ext_ident_double_57,
                             const SDouble ext_minimal_horizontal_separation,
                             const SDouble ext_ident_double_60)
{
  const SDouble s0 = ext_ownship_position_x;
  const SDouble s1 = ext_intruder_position_x;
  const SDouble s2 = ext_ownship_planned_velocity_x;
  const SDouble s3 = ext_intruder_velocity_x;
  const SDouble s4 = ext_ownship_position_y;
  const SDouble s5 = ext_intruder_position_y;
  const SDouble s6 = ext_ownship_planned_velocity_y;
  const SDouble s7 = ext_intruder_velocity_y;
  const SDouble s8 = ext_direction_parameter_horizontal;
  const SDouble s9 = ext_ident_double_59;
  const SDouble s13 = ext_ident_double_60;
  const SDouble s14 = s0 - s1;
  const SDouble s15 = s2 - s3;
  const SDouble s16 = s14 * s15;
  const SDouble s17 = s4 - s5;
  const SDouble s18 = s6 - s7;
  const SDouble s19 = s17 * s18;
  const SDouble s20 = s16 + s19;
  const SDouble s21 = s9 / s13;
  const SDouble s22 = s8 * s21;
  const SDouble s23 = s14 * s18;
  const SDouble s24 = s15 * s17;
  const SDouble s25 = s23 - s24;
  const SDouble s26 = s22 * s25;
  const SBool   s27 = s20 >= s26;
  const SBool   s28 = s27 /* criterion3D_part2 */;

  return s28;
}
