/* File: "ext_ident_double_3_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: exitDotMin_dividend",color=plum, style=filled]
0 -> 1
2 [label="ext_sqrt_2",color=cyan4, style=filled]
1 -> 2


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((ext_sqrt_2));
*/
SDouble ext_ident_double_3_arg0(const SDouble ext_sqrt_2,
                                const SDouble ext_ident_double_1,
                                const SDouble ext_ownship_position_x,
                                const SDouble ext_intruder_position_x,
                                const SDouble ext_ownship_position_y,
                                const SDouble ext_intruder_position_y)
{
  const SDouble s0 = ext_sqrt_2;
  const SDouble s6 = s0 /* exitDotMin_dividend */;

  return s6;
}
