/* File: "ext_ident_bool_390_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "criterion3D_part4" ((Extf_ident_double(label "normsq2dim" (((Ext_ownship_position_x - Ext_intruder_position_x) * (Ext_ownship_position_x - Ext_intruder_position_x)) + ((Ext_ownship_position_y - Ext_intruder_position_y) * (Ext_ownship_position_y - Ext_intruder_position_y)))) < (Ext_minimal_horizontal_separation * Ext_minimal_horizontal_separation)) || Extf_ident_bool(label "criterion3D_part5" ((((Ext_ownship_position_x - Ext_intruder_position_x) * ((Ext_ownship_planned_velocity_x - Ext_intruder_velocity_x) - (Ext_ownship_velocity_x - Ext_intruder_velocity_x))) + ((Ext_ownship_position_y - Ext_intruder_position_y) * ((Ext_ownship_planned_velocity_y - Ext_intruder_velocity_y) - (Ext_ownship_velocity_y - Ext_intruder_velocity_y)))) >= ((Ext_direction_parameter_horizontal * (Extf_ident_double(label "hor_rr_dividend" Extf_sqrt((Extf_ident_double(label "normsq2dim" (((Ext_ownship_position_x - Ext_intruder_position_x) * (Ext_ownship_position_x - Ext_intruder_position_x)) + ((Ext_ownship_position_y - Ext_intruder_position_y) * (Ext_ownship_position_y - Ext_intruder_position_y)))) - (Ext_minimal_horizontal_separation * Ext_minimal_horizontal_separation)))) / Extf_ident_double(label "hor_rr_divisor" Ext_minimal_horizontal_separation))) * (((Ext_ownship_position_x - Ext_intruder_position_x) * ((Ext_ownship_planned_velocity_y - Ext_intruder_velocity_y) - (Ext_ownship_velocity_y - Ext_intruder_velocity_y))) - (((Ext_ownship_planned_velocity_x - Ext_intruder_velocity_x) - (Ext_ownship_velocity_x - Ext_intruder_velocity_x)) * (Ext_ownship_position_y - Ext_intruder_position_y)))))))
*/
/*@
 assigns \nothing;
 ensures \result == ((((((ext_ident_double_384) < (((ext_minimal_horizontal_separation) * (ext_minimal_horizontal_separation))))) || (ext_ident_bool_389))));
*/
SBool ext_ident_bool_390_arg0(const SDouble ext_ident_double_384,
                              const SDouble ext_ownship_position_x,
                              const SDouble ext_intruder_position_x,
                              const SDouble ext_ownship_position_y,
                              const SDouble ext_intruder_position_y,
                              const SDouble ext_minimal_horizontal_separation,
                              const SBool ext_ident_bool_389,
                              const SDouble ext_ownship_planned_velocity_x,
                              const SDouble ext_intruder_velocity_x,
                              const SDouble ext_ownship_velocity_x,
                              const SDouble ext_ownship_planned_velocity_y,
                              const SDouble ext_intruder_velocity_y,
                              const SDouble ext_ownship_velocity_y,
                              const SDouble ext_direction_parameter_horizontal,
                              const SDouble ext_ident_double_387, const SDouble ext_sqrt_386,
                              const SDouble ext_ident_double_385,
                              const SDouble ext_ident_double_388)
{
  const SDouble s0 = ext_ident_double_384;
  const SDouble s1 = ext_ownship_position_x;
  const SDouble s2 = ext_intruder_position_x;
  const SDouble s3 = ext_ownship_position_y;
  const SDouble s4 = ext_intruder_position_y;
  const SDouble s5 = ext_minimal_horizontal_separation;
  const SBool   s6 = ext_ident_bool_389;
  const SDouble s7 = ext_ownship_planned_velocity_x;
  const SDouble s8 = ext_intruder_velocity_x;
  const SDouble s9 = ext_ownship_velocity_x;
  const SDouble s10 = ext_ownship_planned_velocity_y;
  const SDouble s11 = ext_intruder_velocity_y;
  const SDouble s12 = ext_ownship_velocity_y;
  const SDouble s13 = ext_direction_parameter_horizontal;
  const SDouble s14 = ext_ident_double_387;
  const SDouble s15 = ext_sqrt_386;
  const SDouble s16 = ext_ident_double_385;
  const SDouble s17 = ext_ident_double_388;
  const SDouble s18 = s5 * s5;
  const SBool   s19 = s0 < s18;
  const SBool   s20 = s6 || s19;
  const SBool   s21 = s20 /* criterion3D_part4 */;

  return s21;
}
