/* File: "ext_ident_double_134_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: dirVert",color=plum, style=filled]
0 -> 1
2 [label="op3: mux",color=green4, style=filled]
1 -> 2
3 [label="ext_ident_bool_131",color=cyan4, style=filled]
2 -> 3
23 [label="ext_ident_double_133",color=cyan4, style=filled]
2 -> 23
33 [label="const: -1.0",color=red1, style=filled]
2 -> 33


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((( (ext_ident_bool_131) ? (ext_ident_double_133) : (-1.0))));
*/
SDouble ext_ident_double_134_arg0(const SBool ext_ident_bool_131,
                                  const SDouble ext_ident_double_130,
                                  const SDouble ext_ident_double_127,
                                  const SDouble ext_ownship_position_z,
                                  const SDouble ext_intruder_position_z,
                                  const SDouble ext_ident_double_129,
                                  const SDouble ext_ident_double_128,
                                  const SDouble ext_minimal_vertical_separation,
                                  const SDouble ext_ident_double_133,
                                  const SDouble ext_direction_parameter_vertical,
                                  const SDouble ext_ident_double_132)
{
  const SBool   s0 = ext_ident_bool_131;
  const SDouble s8 = ext_ident_double_133;
  const SDouble s12 = s0 ? s8 : -1.0;
  const SDouble s13 = s12 /* dirVert */;

  return s13;
}
