/* File: "ext_ident_bool_7_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: horizontalCriterionLoss_part2",color=plum, style=filled]
0 -> 1
2 [label="op2: >",color=green4, style=filled]
1 -> 2
3 [label="op2: +",color=green4, style=filled]
2 -> 3
4 [label="op2: *",color=green4, style=filled]
3 -> 4
5 [label="op2: -",color=green4, style=filled]
4 -> 5
6 [label="ext_ownship_position_x",color=cyan1, style=filled]
5 -> 6
7 [label="ext_intruder_position_x",color=cyan1, style=filled]
5 -> 7
8 [label="op2: -",color=green4, style=filled]
4 -> 8
9 [label="ext_ownship_planned_velocity_x",color=cyan1, style=filled]
8 -> 9
10 [label="ext_intruder_velocity_x",color=cyan1, style=filled]
8 -> 10
11 [label="op2: *",color=green4, style=filled]
3 -> 11
12 [label="op2: -",color=green4, style=filled]
11 -> 12
13 [label="ext_ownship_position_y",color=cyan1, style=filled]
12 -> 13
14 [label="ext_intruder_position_y",color=cyan1, style=filled]
12 -> 14
15 [label="op2: -",color=green4, style=filled]
11 -> 15
16 [label="ext_ownship_planned_velocity_y",color=cyan1, style=filled]
15 -> 16
17 [label="ext_intruder_velocity_y",color=cyan1, style=filled]
15 -> 17
18 [label="op2: *",color=green4, style=filled]
2 -> 18
19 [label="op2: /",color=green4, style=filled]
18 -> 19
20 [label="ext_ident_double_3",color=cyan4, style=filled]
19 -> 20
40 [label="ext_ident_double_4",color=cyan4, style=filled]
19 -> 40
43 [label="op2: -",color=green4, style=filled]
18 -> 43
44 [label="ext_minimal_horizontal_separation",color=cyan1, style=filled]
43 -> 44
45 [label="ext_sqrt_6",color=cyan4, style=filled]
43 -> 45


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((((((((((ext_ownship_position_x) - (ext_intruder_position_x))) * (((ext_ownship_planned_velocity_x) - (ext_intruder_velocity_x))))) + (((((ext_ownship_position_y) - (ext_intruder_position_y))) * (((ext_ownship_planned_velocity_y) - (ext_intruder_velocity_y))))))) > (((((ext_ident_double_3) / (ext_ident_double_4))) * (((ext_minimal_horizontal_separation) - (ext_sqrt_6))))))));
*/
SBool ext_ident_bool_7_arg0(const SDouble ext_ownship_position_x,
                            const SDouble ext_intruder_position_x,
                            const SDouble ext_ownship_planned_velocity_x,
                            const SDouble ext_intruder_velocity_x,
                            const SDouble ext_ownship_position_y,
                            const SDouble ext_intruder_position_y,
                            const SDouble ext_ownship_planned_velocity_y,
                            const SDouble ext_intruder_velocity_y,
                            const SDouble ext_ident_double_3, const SDouble ext_sqrt_2,
                            const SDouble ext_ident_double_1, const SDouble ext_ident_double_4,
                            const SDouble ext_maximum_time_for_violation,
                            const SDouble ext_minimal_horizontal_separation,
                            const SDouble ext_sqrt_6, const SDouble ext_ident_double_5)
{
  const SDouble s0 = ext_ownship_position_x;
  const SDouble s1 = ext_intruder_position_x;
  const SDouble s2 = ext_ownship_planned_velocity_x;
  const SDouble s3 = ext_intruder_velocity_x;
  const SDouble s4 = ext_ownship_position_y;
  const SDouble s5 = ext_intruder_position_y;
  const SDouble s6 = ext_ownship_planned_velocity_y;
  const SDouble s7 = ext_intruder_velocity_y;
  const SDouble s8 = ext_ident_double_3;
  const SDouble s11 = ext_ident_double_4;
  const SDouble s13 = ext_minimal_horizontal_separation;
  const SDouble s14 = ext_sqrt_6;
  const SDouble s16 = s0 - s1;
  const SDouble s17 = s2 - s3;
  const SDouble s18 = s16 * s17;
  const SDouble s19 = s4 - s5;
  const SDouble s20 = s6 - s7;
  const SDouble s21 = s19 * s20;
  const SDouble s22 = s18 + s21;
  const SDouble s23 = s8 / s11;
  const SDouble s24 = s13 - s14;
  const SDouble s25 = s23 * s24;
  const SBool   s26 = s22 > s25;
  const SBool   s27 = s26 /* horizontalCriterionLoss_part2 */;

  return s27;
}
