/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */


/* Triggers (must be defined by user): */

void alert_inconsistent_data_from_me();

/* External variables (must be defined by user): */

extern uint64_t my_timestamp;
extern double my_latitude;
extern double my_longitude;
extern uint64_t my_ICAO24;
extern uint64_t my_altitude;
extern uint64_t my_groundspeed;
extern uint64_t my_heading;
extern bool my_AGflag;

/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step(void);