/* File: "ext_ident_double_146_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "criterion3D_part1.2" Extf_ident_double(label "normsq2dim" (((Extf_ident_double(label "ownPositionX" (if s0 then Ext_ownship_position_x else s1)) - Extf_ident_double(label "intPositionX" (if s0 then Ext_intruder_position_x else s2))) * (Extf_ident_double(label "ownPositionX" (if s0 then Ext_ownship_position_x else s1)) - Extf_ident_double(label "intPositionX" (if s0 then Ext_intruder_position_x else s2)))) + ((Extf_ident_double(label "ownPositionY" (if s0 then Ext_ownship_position_y else s4)) - Extf_ident_double(label "intPositionY" (if s0 then Ext_intruder_position_y else s5))) * (Extf_ident_double(label "ownPositionY" (if s0 then Ext_ownship_position_y else s4)) - Extf_ident_double(label "intPositionY" (if s0 then Ext_intruder_position_y else s5))))))
*/
/*@
 assigns \nothing;
 ensures \result == ((ext_ident_double_145));
*/
SDouble ext_ident_double_146_arg0(const SDouble ext_ident_double_145,
                                  const SDouble ext_ident_double_137, const SBool *queue_0,
                                  const SWord32 ptr_0, const SDouble ext_ownship_position_x,
                                  const SDouble *queue_1, const SWord32 ptr_1,
                                  const SDouble ext_ident_double_138,
                                  const SDouble ext_intruder_position_x, const SDouble *queue_2,
                                  const SWord32 ptr_2, const SDouble ext_ident_double_139,
                                  const SDouble ext_ident_double_140,
                                  const SDouble ext_ident_double_141,
                                  const SDouble ext_ownship_position_y, const SDouble *queue_4,
                                  const SWord32 ptr_4, const SDouble ext_ident_double_142,
                                  const SDouble ext_intruder_position_y, const SDouble *queue_5,
                                  const SWord32 ptr_5, const SDouble ext_ident_double_143,
                                  const SDouble ext_ident_double_144)
{
  const SDouble s0 = ext_ident_double_145;
  const SDouble s1 = ext_ident_double_137;
  const SBool   s2 = queue_0[0];
  const SWord32 s3 = ptr_0;
  const SDouble s4 = ext_ownship_position_x;
  const SDouble s5 = queue_1[0];
  const SWord32 s6 = ptr_1;
  const SDouble s7 = ext_ident_double_138;
  const SDouble s8 = ext_intruder_position_x;
  const SDouble s9 = queue_2[0];
  const SWord32 s10 = ptr_2;
  const SDouble s11 = ext_ident_double_139;
  const SDouble s12 = ext_ident_double_140;
  const SDouble s13 = ext_ident_double_141;
  const SDouble s14 = ext_ownship_position_y;
  const SDouble s15 = queue_4[0];
  const SWord32 s16 = ptr_4;
  const SDouble s17 = ext_ident_double_142;
  const SDouble s18 = ext_intruder_position_y;
  const SDouble s19 = queue_5[0];
  const SWord32 s20 = ptr_5;
  const SDouble s21 = ext_ident_double_143;
  const SDouble s22 = ext_ident_double_144;
  const SDouble s23 = s0 /* criterion3D_part1.2 */;

  return s23;
}
