/* File: "ext_ident_double_499_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "dirVert_part1.1" (Extf_ident_double(label "dirVert_part1.1.1" (Extf_ident_double(label "ownPositionZ" (if s0 then Ext_ownship_position_z else s9)) - Extf_ident_double(label "intPositionZ" (if s0 then Ext_intruder_position_z else s10)))) * Extf_ident_double(label "absolute_value_splitting" signum Extf_ident_double(label "dirVert_part1.1.1" (Extf_ident_double(label "ownPositionZ" (if s0 then Ext_ownship_position_z else s9)) - Extf_ident_double(label "intPositionZ" (if s0 then Ext_intruder_position_z else s10))))))
*/
/*@
 assigns \nothing;
 ensures \result == ((((ext_ident_double_494) * (ext_ident_double_498))));
*/
SDouble ext_ident_double_499_arg0(const SDouble ext_ident_double_494,
                                  const SDouble ext_ident_double_492, const SBool *queue_0,
                                  const SWord32 ptr_0, const SDouble ext_ownship_position_z,
                                  const SDouble *queue_9, const SWord32 ptr_9,
                                  const SDouble ext_ident_double_493,
                                  const SDouble ext_intruder_position_z, const SDouble *queue_10,
                                  const SWord32 ptr_10, const SDouble ext_ident_double_498,
                                  const SDouble ext_ident_double_497,
                                  const SDouble ext_ident_double_495,
                                  const SDouble ext_ident_double_496)
{
  const SDouble s0 = ext_ident_double_494;
  const SDouble s1 = ext_ident_double_492;
  const SBool   s2 = queue_0[0];
  const SWord32 s3 = ptr_0;
  const SDouble s4 = ext_ownship_position_z;
  const SDouble s5 = queue_9[0];
  const SWord32 s6 = ptr_9;
  const SDouble s7 = ext_ident_double_493;
  const SDouble s8 = ext_intruder_position_z;
  const SDouble s9 = queue_10[0];
  const SWord32 s10 = ptr_10;
  const SDouble s11 = ext_ident_double_498;
  const SDouble s12 = ext_ident_double_497;
  const SDouble s13 = ext_ident_double_495;
  const SDouble s14 = ext_ident_double_496;
  const SDouble s15 = s0 * s11;
  const SDouble s16 = s15 /* dirVert_part1.1 */;

  return s16;
}
