/* File: "ext_ident_double_50_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "verticalCriterionLoss_part1.1" ((Extf_ident_double(label "ownPositionZ" (if s0 then Ext_ownship_position_z else s9)) - Extf_ident_double(label "intPositionZ" (if s0 then Ext_intruder_position_z else s10))) * Extf_ident_double(label "absolute_value_splitting" signum (Extf_ident_double(label "ownPositionZ" (if s0 then Ext_ownship_position_z else s9)) - Extf_ident_double(label "intPositionZ" (if s0 then Ext_intruder_position_z else s10)))))
*/
/*@
 assigns \nothing;
 ensures \result == ((((((ext_ident_double_45) - (ext_ident_double_46))) * (ext_ident_double_49))));
*/
SDouble ext_ident_double_50_arg0(const SDouble ext_ident_double_45,
                                 const SBool *queue_0, const SWord32 ptr_0,
                                 const SDouble ext_ownship_position_z, const SDouble *queue_9,
                                 const SWord32 ptr_9, const SDouble ext_ident_double_46,
                                 const SDouble ext_intruder_position_z, const SDouble *queue_10,
                                 const SWord32 ptr_10, const SDouble ext_ident_double_49,
                                 const SDouble ext_ident_double_47,
                                 const SDouble ext_ident_double_48)
{
  const SDouble s0 = ext_ident_double_45;
  const SBool   s1 = queue_0[0];
  const SWord32 s2 = ptr_0;
  const SDouble s3 = ext_ownship_position_z;
  const SDouble s4 = queue_9[0];
  const SWord32 s5 = ptr_9;
  const SDouble s6 = ext_ident_double_46;
  const SDouble s7 = ext_intruder_position_z;
  const SDouble s8 = queue_10[0];
  const SWord32 s9 = ptr_10;
  const SDouble s10 = ext_ident_double_49;
  const SDouble s11 = ext_ident_double_47;
  const SDouble s12 = ext_ident_double_48;
  const SDouble s13 = s0 - s6;
  const SDouble s14 = s10 * s13;
  const SDouble s15 = s14 /* verticalCriterionLoss_part1.1 */;

  return s15;
}
