/* File: "ext_ident_bool_55_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*ACSL to write
 label "zCriterion_part1.2" ((Ext_ownship_velocity_z - Extf_ident_double(label "intVelocityZ" (if s0 then Ext_intruder_velocity_z else s11))) > 0.0)
*/
/*@
 assigns \nothing;
 ensures \result == ((((((ext_ownship_velocity_z) - (ext_ident_double_54))) > (0.0))));
*/
SBool ext_ident_bool_55_arg0(const SDouble ext_ownship_velocity_z,
                             const SDouble ext_ident_double_54, const SBool *queue_0,
                             const SWord32 ptr_0, const SDouble ext_intruder_velocity_z,
                             const SDouble *queue_11, const SWord32 ptr_11)
{
  const SDouble s0 = ext_ownship_velocity_z;
  const SDouble s1 = ext_ident_double_54;
  const SBool   s2 = queue_0[0];
  const SWord32 s3 = ptr_0;
  const SDouble s4 = ext_intruder_velocity_z;
  const SDouble s5 = queue_11[0];
  const SWord32 s6 = ptr_11;
  const SDouble s7 = s0 - s1;
  const SBool   s9 = s7 > 0.0;
  const SBool   s10 = s9 /* zCriterion_part1.2 */;

  return s10;
}
