/* File: "update_state_9.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*ACSL to write
 Ext_ownship_position_z
*/
/*@
 assigns \nothing;
 ensures \result == (ext_ownship_position_z);
*/
SDouble update_state_9(const SDouble ext_ownship_position_z)
{
  const SDouble s0 = ext_ownship_position_z;
  return s0;
}
