/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */

extern bool i;

/* Triggers (must be defined by user): */

void h(int8_t);
void g(uint64_t);
void f(uint64_t, uint64_t);
void e(uint64_t, uint64_t, uint64_t, uint8_t);

/* External variables (must be defined by user): */

extern uint64_t e3;
extern uint64_t e1;
extern uint64_t e2;

/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step(void);