/* File: "update_state_1.c". Automatically generated by SBV. Do not edit! */

#include <inttypes.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "internal.h"

/* User given declarations: */
/*test 001*/
/*ACSL to write
 (if s2 then not s1 else s1)
*/
/*@
 assigns \nothing;
 ensures \result == (( (queue_2[ptr_2]) ? (! ((queue_1[ptr_1]))) : (queue_1[ptr_1])));
*/
SBool update_state_1(const SBool *queue_2, const SWord32 ptr_2,
                     const SBool *queue_1, const SWord32 ptr_1)
{
  const SBool   s0 = queue_2[0];
  const SBool   s1 = queue_2[1];
  const SBool   s2 = queue_2[2];
  const SWord32 s3 = ptr_2;
  const SBool   s4 = queue_1[0];
  const SWord32 s5 = ptr_1;
  const SBool table0[] = {
      s0, s1, s2
  };
  const SWord32 s7 = (0x00000003UL == 0) ? 0 : (s3 % 0x00000003UL);
  const SBool   s8 = table0[s7];
  const SBool   s9 = !s4;
  const SBool   s10 = s8 ? s9 : s4;

  return s10;
}
