/* Header file for internal. Automatically generated by SBV. Do not edit! */

#ifndef __internal__HEADER_INCLUDED__
#define __internal__HEADER_INCLUDED__

#include <inttypes.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>

/* The boolean type */
typedef bool SBool;

/* The float type */
typedef float SFloat;

/* The double type */
typedef double SDouble;

/* Unsigned bit-vectors */
typedef uint8_t  SWord8 ;
typedef uint16_t SWord16;
typedef uint32_t SWord32;
typedef uint64_t SWord64;

/* Signed bit-vectors */
typedef int8_t  SInt8 ;
typedef int16_t SInt16;
typedef int32_t SInt32;
typedef int64_t SInt64;

/* Entry point prototypes: */
SWord32 update_state_1(const SWord32 *queue_1,
                       const SWord32 ptr_1);
SWord32 update_state_4(const SWord32 *queue_4,
                       const SWord32 ptr_4);
SWord32 update_state_8(const SWord32 *queue_8,
                       const SWord32 ptr_8);
SWord32 update_state_12(const SWord32 *queue_12,
                        const SWord32 ptr_12);
SWord32 update_state_16(const SWord32 *queue_16,
                        const SWord32 ptr_16);
SWord32 update_state_20(const SWord32 *queue_20,
                        const SWord32 ptr_20);
SWord32 update_state_24(const SWord32 *queue_24,
                        const SWord32 ptr_24);
SWord32 update_state_28(const SWord32 *queue_28,
                        const SWord32 ptr_28);
SWord32 update_state_32(const SWord32 *queue_32,
                        const SWord32 ptr_32);
SWord32 update_state_36(const SWord32 *queue_36,
                        const SWord32 ptr_36);
SWord32 update_state_40(const SWord32 *queue_40,
                        const SWord32 ptr_40);
SWord32 update_state_44(const SWord32 *queue_44,
                        const SWord32 ptr_44);
SWord32 update_state_48(const SWord32 *queue_48,
                        const SWord32 ptr_48);
SWord32 update_state_52(const SWord32 *queue_52,
                        const SWord32 ptr_52);
SWord32 update_state_56(const SWord32 *queue_56,
                        const SWord32 ptr_56);
SWord32 update_state_60(const SWord32 *queue_60,
                        const SWord32 ptr_60);
SWord32 update_state_64(const SWord32 *queue_64,
                        const SWord32 ptr_64);
SWord32 update_state_68(const SWord32 *queue_68,
                        const SWord32 ptr_68);
SWord32 update_state_72(const SWord32 *queue_72,
                        const SWord32 ptr_72);
SWord32 update_state_76(const SWord32 *queue_76,
                        const SWord32 ptr_76);
SWord32 update_state_80(const SWord32 *queue_80,
                        const SWord32 ptr_80);
SWord32 update_state_84(const SWord32 *queue_84,
                        const SWord32 ptr_84);
SWord32 update_state_88(const SWord32 *queue_88,
                        const SWord32 ptr_88);
SWord32 update_state_92(const SWord32 *queue_92,
                        const SWord32 ptr_92);
SWord32 update_state_96(const SWord32 *queue_96,
                        const SWord32 ptr_96);
SWord32 update_state_100(const SWord32 *queue_100,
                         const SWord32 ptr_100);
SBool trigger_guard_aMaj();
SBool trigger_aMaj_arg_0(const SWord32 *queue_1,
                         const SWord32 ptr_1, const SWord32 *queue_4, const SWord32 ptr_4,
                         const SWord32 *queue_8, const SWord32 ptr_8,
                         const SWord32 *queue_12, const SWord32 ptr_12,
                         const SWord32 *queue_16, const SWord32 ptr_16,
                         const SWord32 *queue_20, const SWord32 ptr_20,
                         const SWord32 *queue_24, const SWord32 ptr_24,
                         const SWord32 *queue_28, const SWord32 ptr_28,
                         const SWord32 *queue_32, const SWord32 ptr_32,
                         const SWord32 *queue_36, const SWord32 ptr_36,
                         const SWord32 *queue_40, const SWord32 ptr_40,
                         const SWord32 *queue_44, const SWord32 ptr_44,
                         const SWord32 *queue_48, const SWord32 ptr_48,
                         const SWord32 *queue_52, const SWord32 ptr_52,
                         const SWord32 *queue_56, const SWord32 ptr_56,
                         const SWord32 *queue_60, const SWord32 ptr_60,
                         const SWord32 *queue_64, const SWord32 ptr_64,
                         const SWord32 *queue_68, const SWord32 ptr_68,
                         const SWord32 *queue_72, const SWord32 ptr_72,
                         const SWord32 *queue_76, const SWord32 ptr_76,
                         const SWord32 *queue_80, const SWord32 ptr_80,
                         const SWord32 *queue_84, const SWord32 ptr_84,
                         const SWord32 *queue_88, const SWord32 ptr_88,
                         const SWord32 *queue_92, const SWord32 ptr_92,
                         const SWord32 *queue_96, const SWord32 ptr_96,
                         const SWord32 *queue_100, const SWord32 ptr_100);
SBool trigger_guard_maj();
SWord32 trigger_maj_arg_0(const SWord32 *queue_4,
                          const SWord32 ptr_4, const SWord32 *queue_1, const SWord32 ptr_1,
                          const SWord32 *queue_8, const SWord32 ptr_8,
                          const SWord32 *queue_12, const SWord32 ptr_12,
                          const SWord32 *queue_16, const SWord32 ptr_16,
                          const SWord32 *queue_20, const SWord32 ptr_20,
                          const SWord32 *queue_24, const SWord32 ptr_24,
                          const SWord32 *queue_28, const SWord32 ptr_28,
                          const SWord32 *queue_32, const SWord32 ptr_32,
                          const SWord32 *queue_36, const SWord32 ptr_36,
                          const SWord32 *queue_40, const SWord32 ptr_40,
                          const SWord32 *queue_44, const SWord32 ptr_44,
                          const SWord32 *queue_48, const SWord32 ptr_48,
                          const SWord32 *queue_52, const SWord32 ptr_52,
                          const SWord32 *queue_56, const SWord32 ptr_56,
                          const SWord32 *queue_60, const SWord32 ptr_60,
                          const SWord32 *queue_64, const SWord32 ptr_64,
                          const SWord32 *queue_68, const SWord32 ptr_68,
                          const SWord32 *queue_72, const SWord32 ptr_72,
                          const SWord32 *queue_76, const SWord32 ptr_76,
                          const SWord32 *queue_80, const SWord32 ptr_80,
                          const SWord32 *queue_84, const SWord32 ptr_84,
                          const SWord32 *queue_88, const SWord32 ptr_88,
                          const SWord32 *queue_92, const SWord32 ptr_92,
                          const SWord32 *queue_96, const SWord32 ptr_96,
                          const SWord32 *queue_100, const SWord32 ptr_100);

#endif /* __internal__HEADER_INCLUDED__ */
