/* Generated by Copilot Core. */

#include <stdint.h>
#include <stdbool.h>

/* Observers (defined by Copilot): */

extern bool reset;
extern bool test2;
extern bool test1;

/* Triggers (must be defined by user): */


/* External variables (must be defined by user): */

extern int8_t e;

/* External arrays (must be defined by user): */


/* External functions (must be defined by user): */


/* Step function: */

void step();