/* File: "update_state_36.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/*ACSL following*/
/*test 001*/
/*ACSL to write
 ((extern "e" == 1) && ((((if s0 then s37 else s38) || (if s0 then s33 else s34)) || (if s0 then s35 else s36)) || (if s0 then s31 else s32)))
*/
/*@
 assigns \nothing;
 ensures \result == ((ext_e == 1) && (((( queue_0[ptr_0] ? queue_37[ptr_37] : queue_38[ptr_38]) || ( queue_0[ptr_0] ? queue_33[ptr_33] : queue_34[ptr_34])) || ( queue_0[ptr_0] ? queue_35[ptr_35] : queue_36[ptr_36])) || ( queue_0[ptr_0] ? queue_31[ptr_31] : queue_32[ptr_32])));
*/
SBool update_state_36(const SInt8 ext_e, const SBool *queue_0,
                      const SWord32 ptr_0, const SBool *queue_37, const SWord32 ptr_37,
                      const SBool *queue_38, const SWord32 ptr_38, const SBool *queue_33,
                      const SWord32 ptr_33, const SBool *queue_34, const SWord32 ptr_34,
                      const SBool *queue_35, const SWord32 ptr_35, const SBool *queue_36,
                      const SWord32 ptr_36, const SBool *queue_31, const SWord32 ptr_31,
                      const SBool *queue_32, const SWord32 ptr_32)
{
  const SInt8 s0 = ext_e;
  const SBool s1 = queue_0[0];
  const SWord32 s2 = ptr_0;
  const SBool s3 = queue_37[0];
  const SWord32 s4 = ptr_37;
  const SBool s5 = queue_38[0];
  const SWord32 s6 = ptr_38;
  const SBool s7 = queue_33[0];
  const SWord32 s8 = ptr_33;
  const SBool s9 = queue_34[0];
  const SWord32 s10 = ptr_34;
  const SBool s11 = queue_35[0];
  const SWord32 s12 = ptr_35;
  const SBool s13 = queue_36[0];
  const SWord32 s14 = ptr_36;
  const SBool s15 = queue_31[0];
  const SWord32 s16 = ptr_31;
  const SBool s17 = queue_32[0];
  const SWord32 s18 = ptr_32;
  const SBool s20 = s0 == 1;
  const SBool s21 = s1 ? s3 : s5;
  const SBool s22 = s1 ? s7 : s9;
  const SBool s23 = s21 || s22;
  const SBool s24 = s1 ? s11 : s13;
  const SBool s25 = s23 || s24;
  const SBool s26 = s1 ? s15 : s17;
  const SBool s27 = s25 || s26;
  const SBool s28 = s20 && s27;

  return s28;
}
