/* File: "update_state_43.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/*ACSL following*/
/*test 001*/
/*ACSL to write
 false
*/
/*@
 assigns \nothing;
 ensures \result == false;
*/
SBool update_state_43()
{
  return false;
}
