/* File: "ext_sqrt_58_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: ?delta",color=plum, style=filled]
0 -> 1
2 [label="op2: -",color=green4, style=filled]
1 -> 2
3 [label="op2: *",color=green4, style=filled]
2 -> 3
4 [label="op2: *",color=green4, style=filled]
3 -> 4
5 [label="label: ?nm",color=plum, style=filled]
4 -> 5
6 [label="const: 1852.0",color=red1, style=filled]
5 -> 6
7 [label="label: ?nm",color=plum, style=filled]
4 -> 7
8 [label="const: 1852.0",color=red1, style=filled]
7 -> 8
9 [label="label: ?normsq2dim",color=plum, style=filled]
3 -> 9
10 [label="label: ?scalar2dim",color=plum, style=filled]
9 -> 10
11 [label="op2: +",color=green4, style=filled]
10 -> 11
12 [label="op2: *",color=green4, style=filled]
11 -> 12
13 [label="op2: -",color=green4, style=filled]
12 -> 13
14 [label="label: ?ownVelocityX",color=plum, style=filled]
13 -> 14
15 [label="ext_ownship_vx",color=cyan1, style=filled]
14 -> 15
16 [label="label: ?intVelocityX",color=plum, style=filled]
13 -> 16
17 [label="ext_intruder_vx",color=cyan1, style=filled]
16 -> 17
18 [label="op2: -",color=green4, style=filled]
12 -> 18
19 [label="label: ?ownVelocityX",color=plum, style=filled]
18 -> 19
20 [label="ext_ownship_vx",color=cyan1, style=filled]
19 -> 20
21 [label="label: ?intVelocityX",color=plum, style=filled]
18 -> 21
22 [label="ext_intruder_vx",color=cyan1, style=filled]
21 -> 22
23 [label="op2: *",color=green4, style=filled]
11 -> 23
24 [label="op2: -",color=green4, style=filled]
23 -> 24
25 [label="label: ?ownVelocityY",color=plum, style=filled]
24 -> 25
26 [label="ext_ownship_vy",color=cyan1, style=filled]
25 -> 26
27 [label="label: ?intVelocityY",color=plum, style=filled]
24 -> 27
28 [label="ext_intruder_vy",color=cyan1, style=filled]
27 -> 28
29 [label="op2: -",color=green4, style=filled]
23 -> 29
30 [label="label: ?ownVelocityY",color=plum, style=filled]
29 -> 30
31 [label="ext_ownship_vy",color=cyan1, style=filled]
30 -> 31
32 [label="label: ?intVelocityY",color=plum, style=filled]
29 -> 32
33 [label="ext_intruder_vy",color=cyan1, style=filled]
32 -> 33
34 [label="op2: *",color=green4, style=filled]
2 -> 34
35 [label="label: ?det2dim",color=plum, style=filled]
34 -> 35
36 [label="op2: -",color=green4, style=filled]
35 -> 36
37 [label="op2: *",color=green4, style=filled]
36 -> 37
38 [label="op2: -",color=green4, style=filled]
37 -> 38
39 [label="label: ?ownPositionX",color=plum, style=filled]
38 -> 39
40 [label="op2: *",color=green4, style=filled]
39 -> 40
41 [label="const: 6371000.0",color=red1, style=filled]
40 -> 41
42 [label="label: ?ownLong",color=plum, style=filled]
40 -> 42
43 [label="op2: *",color=green4, style=filled]
42 -> 43
44 [label="ext_ownship_longitude",color=cyan1, style=filled]
43 -> 44
45 [label="label: ?deg",color=plum, style=filled]
43 -> 45
46 [label="op2: /",color=green4, style=filled]
45 -> 46
47 [label="label: ?pi",color=plum, style=filled]
46 -> 47
48 [label="const: 3.141592653589793",color=red1, style=filled]
47 -> 48
49 [label="const: 180.0",color=red1, style=filled]
46 -> 49
50 [label="label: ?intPositionX",color=plum, style=filled]
38 -> 50
51 [label="op2: *",color=green4, style=filled]
50 -> 51
52 [label="const: 6371000.0",color=red1, style=filled]
51 -> 52
53 [label="label: ?intLong",color=plum, style=filled]
51 -> 53
54 [label="op2: *",color=green4, style=filled]
53 -> 54
55 [label="ext_intruder_longitude",color=cyan1, style=filled]
54 -> 55
56 [label="label: ?deg",color=plum, style=filled]
54 -> 56
57 [label="op2: /",color=green4, style=filled]
56 -> 57
58 [label="label: ?pi",color=plum, style=filled]
57 -> 58
59 [label="const: 3.141592653589793",color=red1, style=filled]
58 -> 59
60 [label="const: 180.0",color=red1, style=filled]
57 -> 60
61 [label="op2: -",color=green4, style=filled]
37 -> 61
62 [label="label: ?ownVelocityY",color=plum, style=filled]
61 -> 62
63 [label="ext_ownship_vy",color=cyan1, style=filled]
62 -> 63
64 [label="label: ?intVelocityY",color=plum, style=filled]
61 -> 64
65 [label="ext_intruder_vy",color=cyan1, style=filled]
64 -> 65
66 [label="op2: *",color=green4, style=filled]
36 -> 66
67 [label="op2: -",color=green4, style=filled]
66 -> 67
68 [label="label: ?ownVelocityX",color=plum, style=filled]
67 -> 68
69 [label="ext_ownship_vx",color=cyan1, style=filled]
68 -> 69
70 [label="label: ?intVelocityX",color=plum, style=filled]
67 -> 70
71 [label="ext_intruder_vx",color=cyan1, style=filled]
70 -> 71
72 [label="op2: -",color=green4, style=filled]
66 -> 72
73 [label="label: ?ownPositionY",color=plum, style=filled]
72 -> 73
74 [label="op2: *",color=green4, style=filled]
73 -> 74
75 [label="const: 6371000.0",color=red1, style=filled]
74 -> 75
76 [label="ext_log_51",color=cyan4, style=filled]
74 -> 76
93 [label="label: ?intPositionY",color=plum, style=filled]
72 -> 93
94 [label="op2: *",color=green4, style=filled]
93 -> 94
95 [label="const: 6371000.0",color=red1, style=filled]
94 -> 95
96 [label="ext_log_53",color=cyan4, style=filled]
94 -> 96
113 [label="label: ?det2dim",color=plum, style=filled]
34 -> 113
114 [label="op2: -",color=green4, style=filled]
113 -> 114
115 [label="op2: *",color=green4, style=filled]
114 -> 115
116 [label="op2: -",color=green4, style=filled]
115 -> 116
117 [label="label: ?ownPositionX",color=plum, style=filled]
116 -> 117
118 [label="op2: *",color=green4, style=filled]
117 -> 118
119 [label="const: 6371000.0",color=red1, style=filled]
118 -> 119
120 [label="label: ?ownLong",color=plum, style=filled]
118 -> 120
121 [label="op2: *",color=green4, style=filled]
120 -> 121
122 [label="ext_ownship_longitude",color=cyan1, style=filled]
121 -> 122
123 [label="label: ?deg",color=plum, style=filled]
121 -> 123
124 [label="op2: /",color=green4, style=filled]
123 -> 124
125 [label="label: ?pi",color=plum, style=filled]
124 -> 125
126 [label="const: 3.141592653589793",color=red1, style=filled]
125 -> 126
127 [label="const: 180.0",color=red1, style=filled]
124 -> 127
128 [label="label: ?intPositionX",color=plum, style=filled]
116 -> 128
129 [label="op2: *",color=green4, style=filled]
128 -> 129
130 [label="const: 6371000.0",color=red1, style=filled]
129 -> 130
131 [label="label: ?intLong",color=plum, style=filled]
129 -> 131
132 [label="op2: *",color=green4, style=filled]
131 -> 132
133 [label="ext_intruder_longitude",color=cyan1, style=filled]
132 -> 133
134 [label="label: ?deg",color=plum, style=filled]
132 -> 134
135 [label="op2: /",color=green4, style=filled]
134 -> 135
136 [label="label: ?pi",color=plum, style=filled]
135 -> 136
137 [label="const: 3.141592653589793",color=red1, style=filled]
136 -> 137
138 [label="const: 180.0",color=red1, style=filled]
135 -> 138
139 [label="op2: -",color=green4, style=filled]
115 -> 139
140 [label="label: ?ownVelocityY",color=plum, style=filled]
139 -> 140
141 [label="ext_ownship_vy",color=cyan1, style=filled]
140 -> 141
142 [label="label: ?intVelocityY",color=plum, style=filled]
139 -> 142
143 [label="ext_intruder_vy",color=cyan1, style=filled]
142 -> 143
144 [label="op2: *",color=green4, style=filled]
114 -> 144
145 [label="op2: -",color=green4, style=filled]
144 -> 145
146 [label="label: ?ownVelocityX",color=plum, style=filled]
145 -> 146
147 [label="ext_ownship_vx",color=cyan1, style=filled]
146 -> 147
148 [label="label: ?intVelocityX",color=plum, style=filled]
145 -> 148
149 [label="ext_intruder_vx",color=cyan1, style=filled]
148 -> 149
150 [label="op2: -",color=green4, style=filled]
144 -> 150
151 [label="label: ?ownPositionY",color=plum, style=filled]
150 -> 151
152 [label="op2: *",color=green4, style=filled]
151 -> 152
153 [label="const: 6371000.0",color=red1, style=filled]
152 -> 153
154 [label="ext_log_55",color=cyan4, style=filled]
152 -> 154
171 [label="label: ?intPositionY",color=plum, style=filled]
150 -> 171
172 [label="op2: *",color=green4, style=filled]
171 -> 172
173 [label="const: 6371000.0",color=red1, style=filled]
172 -> 173
174 [label="ext_log_57",color=cyan4, style=filled]
172 -> 174


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (((((((((1852.0)) * ((1852.0)))) * ((((((((((ext_ownship_vx)) - ((ext_intruder_vx)))) * ((((ext_ownship_vx)) - ((ext_intruder_vx)))))) + ((((((ext_ownship_vy)) - ((ext_intruder_vy)))) * ((((ext_ownship_vy)) - ((ext_intruder_vy)))))))))))) - (((((((((((((6371000.0) * ((((ext_ownship_longitude) * (((((3.141592653589793)) / (180.0)))))))))) - ((((6371000.0) * ((((ext_intruder_longitude) * (((((3.141592653589793)) / (180.0)))))))))))) * ((((ext_ownship_vy)) - ((ext_intruder_vy)))))) - ((((((ext_ownship_vx)) - ((ext_intruder_vx)))) * ((((((6371000.0) * (ext_log_51)))) - ((((6371000.0) * (ext_log_53))))))))))) * (((((((((((6371000.0) * ((((ext_ownship_longitude) * (((((3.141592653589793)) / (180.0)))))))))) - ((((6371000.0) * ((((ext_intruder_longitude) * (((((3.141592653589793)) / (180.0)))))))))))) * ((((ext_ownship_vy)) - ((ext_intruder_vy)))))) - ((((((ext_ownship_vx)) - ((ext_intruder_vx)))) * ((((((6371000.0) * (ext_log_55)))) - ((((6371000.0) * (ext_log_57))))))))))))))));
*/
SDouble ext_sqrt_58_arg0(const SDouble ext_ownship_vx,
                         const SDouble ext_intruder_vx, const SDouble ext_ownship_vy,
                         const SDouble ext_intruder_vy, const SDouble ext_ownship_longitude,
                         const SDouble ext_intruder_longitude, const SDouble ext_log_51,
                         const SDouble ext_tan_50, const SDouble ext_ownship_latitude,
                         const SDouble ext_log_53, const SDouble ext_tan_52,
                         const SDouble ext_intruder_latitude, const SDouble ext_log_55,
                         const SDouble ext_tan_54, const SDouble ext_log_57,
                         const SDouble ext_tan_56)
{
  const SDouble s0 = ext_ownship_vx;
  const SDouble s1 = ext_intruder_vx;
  const SDouble s2 = ext_ownship_vy;
  const SDouble s3 = ext_intruder_vy;
  const SDouble s4 = ext_ownship_longitude;
  const SDouble s5 = ext_intruder_longitude;
  const SDouble s6 = ext_log_51;
  const SDouble s9 = ext_log_53;
  const SDouble s12 = ext_log_55;
  const SDouble s14 = ext_log_57;
  const SDouble s17 = s0 /* ?ownVelocityX */;
  const SDouble s18 = s1 /* ?intVelocityX */;
  const SDouble s19 = s17 - s18;
  const SDouble s20 = s19 * s19;
  const SDouble s21 = s2 /* ?ownVelocityY */;
  const SDouble s22 = s3 /* ?intVelocityY */;
  const SDouble s23 = s21 - s22;
  const SDouble s24 = s23 * s23;
  const SDouble s25 = s20 + s24;
  const SDouble s26 = s25 /* ?scalar2dim */;
  const SDouble s27 = s26 /* ?normsq2dim */;
  const SDouble s28 = 3429904.0 * s27;
  const SDouble s31 = s4 * 1.7453292519943295e-2;
  const SDouble s32 = s31 /* ?ownLong */;
  const SDouble s33 = 6371000.0 * s32;
  const SDouble s34 = s33 /* ?ownPositionX */;
  const SDouble s35 = s5 * 1.7453292519943295e-2;
  const SDouble s36 = s35 /* ?intLong */;
  const SDouble s37 = 6371000.0 * s36;
  const SDouble s38 = s37 /* ?intPositionX */;
  const SDouble s39 = s34 - s38;
  const SDouble s40 = s23 * s39;
  const SDouble s41 = s6 * 6371000.0;
  const SDouble s42 = s41 /* ?ownPositionY */;
  const SDouble s43 = s9 * 6371000.0;
  const SDouble s44 = s43 /* ?intPositionY */;
  const SDouble s45 = s42 - s44;
  const SDouble s46 = s19 * s45;
  const SDouble s47 = s40 - s46;
  const SDouble s48 = s47 /* ?det2dim */;
  const SDouble s49 = s12 * 6371000.0;
  const SDouble s50 = s49 /* ?ownPositionY */;
  const SDouble s51 = s14 * 6371000.0;
  const SDouble s52 = s51 /* ?intPositionY */;
  const SDouble s53 = s50 - s52;
  const SDouble s54 = s19 * s53;
  const SDouble s55 = s40 - s54;
  const SDouble s56 = s55 /* ?det2dim */;
  const SDouble s57 = s48 * s56;
  const SDouble s58 = s28 - s57;
  const SDouble s59 = s58 /* ?delta */;

  return s59;
}
