/* File: "ext_ident_double_626_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: tcpa",color=plum, style=filled]
0 -> 1
2 [label="op3: mux",color=green4, style=filled]
1 -> 2
3 [label="op2: &&",color=green4, style=filled]
2 -> 3
4 [label="op2: ==",color=green4, style=filled]
3 -> 4
5 [label="op2: -",color=green4, style=filled]
4 -> 5
6 [label="ext_ident_double_603",color=cyan4, style=filled]
5 -> 6
13 [label="ext_ident_double_604",color=cyan4, style=filled]
5 -> 13
20 [label="const: 0.0",color=red1, style=filled]
4 -> 20
21 [label="op2: ==",color=green4, style=filled]
3 -> 21
22 [label="op2: -",color=green4, style=filled]
21 -> 22
23 [label="ext_ident_double_605",color=cyan4, style=filled]
22 -> 23
30 [label="ext_ident_double_606",color=cyan4, style=filled]
22 -> 30
37 [label="const: 0.0",color=red1, style=filled]
21 -> 37
38 [label="const: 0.0",color=red1, style=filled]
2 -> 38
39 [label="op2: /",color=green4, style=filled]
2 -> 39
40 [label="op2: -",color=green4, style=filled]
39 -> 40
41 [label="const: 0.0",color=red1, style=filled]
40 -> 41
42 [label="ext_ident_double_615",color=cyan4, style=filled]
40 -> 42
99 [label="ext_ident_double_625",color=cyan4, style=filled]
39 -> 99


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((( (((((((ext_ident_double_603) - (ext_ident_double_604))) == (0.0))) && (((((ext_ident_double_605) - (ext_ident_double_606))) == (0.0))))) ? (0.0) : (((((0.0) - (ext_ident_double_615))) / (ext_ident_double_625))))));
*/
SDouble ext_ident_double_626_arg0(const SDouble ext_ident_double_603,
                                  const SDouble ext_ownship_vx, const SDouble ext_ident_double_604,
                                  const SDouble ext_intruder_vx, const SDouble ext_ident_double_605,
                                  const SDouble ext_ownship_vy, const SDouble ext_ident_double_606,
                                  const SDouble ext_intruder_vy, const SDouble ext_ident_double_615,
                                  const SDouble ext_ident_double_607,
                                  const SDouble ext_ownship_x_position_ft,
                                  const SDouble ext_ident_double_608,
                                  const SDouble ext_intruder_x_position_ft,
                                  const SDouble ext_ident_double_609,
                                  const SDouble ext_ident_double_610,
                                  const SDouble ext_ident_double_611,
                                  const SDouble ext_ident_double_612,
                                  const SDouble ext_intruder_y_position_ft,
                                  const SDouble ext_ident_double_613,
                                  const SDouble ext_ident_double_614,
                                  const SDouble ext_ident_double_625,
                                  const SDouble ext_ident_double_624,
                                  const SDouble ext_ident_double_616,
                                  const SDouble ext_ident_double_617,
                                  const SDouble ext_ident_double_618,
                                  const SDouble ext_ident_double_619,
                                  const SDouble ext_ident_double_620,
                                  const SDouble ext_ident_double_621,
                                  const SDouble ext_ident_double_622,
                                  const SDouble ext_ident_double_623)
{
  const SDouble s0 = ext_ident_double_603;
  const SDouble s2 = ext_ident_double_604;
  const SDouble s4 = ext_ident_double_605;
  const SDouble s6 = ext_ident_double_606;
  const SDouble s8 = ext_ident_double_615;
  const SDouble s20 = ext_ident_double_625;
  const SDouble s30 = s0 - s2;
  const SBool   s32 = s30 == 0.0;
  const SDouble s33 = s4 - s6;
  const SBool   s34 = 0.0 == s33;
  const SBool   s35 = s32 && s34;
  const SDouble s36 = 0.0 - s8;
  const SDouble s37 = s36 / s20;
  const SDouble s38 = s35 ? 0.0 : s37;
  const SDouble s39 = s38 /* tcpa */;

  return s39;
}
