/* File: "ext_ident_double_893_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: nm",color=plum, style=filled]
0 -> 1
2 [label="const: 1852.0",color=red1, style=filled]
1 -> 2


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((1852.0));
*/
SDouble ext_ident_double_893_arg0()
{
  return 1852.0;
}
