/* File: "ext_ident_double_313_arg0.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="label: normsq2dim",color=plum, style=filled]
0 -> 1
2 [label="ext_ident_double_312",color=cyan4, style=filled]
1 -> 2


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == ((ext_ident_double_312));
*/
SDouble ext_ident_double_313_arg0(const SDouble ext_ident_double_312,
                                  const SDouble ext_ident_double_304, const SDouble ext_ownship_vx,
                                  const SDouble ext_ident_double_305, const SDouble ext_intruder_vx,
                                  const SDouble ext_ident_double_306,
                                  const SDouble ext_ident_double_307,
                                  const SDouble ext_ident_double_308, const SDouble ext_ownship_vy,
                                  const SDouble ext_ident_double_309, const SDouble ext_intruder_vy,
                                  const SDouble ext_ident_double_310,
                                  const SDouble ext_ident_double_311)
{
  const SDouble s0 = ext_ident_double_312;
  const SDouble s13 = s0 /* normsq2dim */;

  return s13;
}
