/* File: "update_state_6.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*ACSL to write
 true
*/
/*@
 assigns \nothing;
 ensures \result == (true);
*/
SBool update_state_6()
{
  return true;
}
