/* File: "trigger_trig1_arg_1.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="op2: +",color=green4, style=filled]
0 -> 1
2 [label="op2: +",color=green4, style=filled]
1 -> 2
3 [label="op2: +",color=green4, style=filled]
2 -> 3
4 [label="ext_e1",color=cyan1, style=filled]
3 -> 4
5 [label="ext_e2",color=cyan1, style=filled]
3 -> 5
6 [label="ext_e3_0",color=cyan3, style=filled]
2 -> 6
10 [label="ext_ff_1",color=cyan4, style=filled]
1 -> 10


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (((((((ext_e1) + (ext_e2))) + (ext_e3_0))) + (ext_ff_1)));
*/
SWord64 trigger_trig1_arg_1(const SWord64 ext_e1,
                            const SWord64 ext_e2, const SWord64 ext_e3_0,
                            const SWord64 ext_ff_1, const SWord8 *queue_1, const SWord32 ptr_1)
{
  const SWord64 s0 = ext_e1;
  const SWord64 s1 = ext_e2;
  const SWord64 s2 = ext_e3_0;
  const SWord64 s3 = ext_ff_1;
  const SWord8  s4 = queue_1[0];
  const SWord8  s5 = queue_1[1];
  const SWord32 s6 = ptr_1;
  const SWord64 s7 = s0 + s1;
  const SWord64 s8 = s2 + s7;
  const SWord64 s9 = s3 + s8;

  return s9;
}
