/* File: "update_state_3.c". Automatically generated by SBV. Do not edit! */

#include <inttypes.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include "internal.h"

/*ACSL following*/
/*test 001*/
/*ACSL to write
 true
*/
/*@
 assigns \nothing;
 ensures \result == true;
*/
SBool update_state_3()
{
  return true;
}
