/* File: "trigger_trigger_arg_1.c". Automatically generated by SBV. Do not edit! */

#include <inttypes.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include "internal.h"


/*@
 assigns \nothing
 ensures \result == ext_func1_2

*/
SBool trigger_trigger_arg_1(const SBool ext_func1_2)
{
  const SBool s0 = ext_func1_2;
  return s0;
}
